### ISSUE TITLE
certificate based authentication error : invalid JWT token

### ISSUE THREAD

**Issue by yogeshronly4u** [AzureAD/azure-activedirectory-library-for-java#101]
I am using adal4j v1.1.2 to get token based on client certificate.

Snippet referred: Why does AcquireToken with ClientCredential fail with invalid_client (ACS50012)?

String AAD_HOST_NAME = "login.windows.net";
String AAD_TENANT_ID = "XXX";
String AAD_TENANT_ENDPOINT = "https://" + AAD_HOST_NAME + "/" + AAD_TENANT_ID + "/";
String AAD_CLIENT_ID = "XXX";
String AAD_RESOURCE_ID = "https://vault.azure.net";
String AAD_CERTIFICATE_PATH = "/XXX.pfx";
String AAD_CERTIFICATE_PASSWORD = "XXX";

ExecutorService service = ExecutorServiceHelper.createThreadPool(1, "azureHSMClientExecutorService-");

KeyStore keystore = KeyStore.getInstance("PKCS12", "SunJSSE");
keystore.load(new FileInputStream(AAD_CERTIFICATE_PATH),AAD_CERTIFICATE_PASSWORD.toCharArray());
String alias = keystore.aliases().nextElement();
PrivateKey key = (PrivateKey) keystore.getKey(alias, AAD_CERTIFICATE_PASSWORD.toCharArray());
X509Certificate cert = (X509Certificate) keystore.getCertificate(alias);
AsymmetricKeyCredential asymmetricKeyCredential = AsymmetricKeyCredential.create(AAD_CLIENT_ID,key, cert);
AuthenticationContext ctx = new AuthenticationContext(AAD_TENANT_ENDPOINT, false, service);
Future<AuthenticationResult> result = ctx.acquireToken(AAD_RESOURCE_ID, asymmetricKeyCredential, null);
AuthenticationResult authenticationResult = result.get();
String token = authenticationResult.getAccessToken();
This results in following auth exception

AuthenticationException: com.microsoft.aad.adal4j.AuthenticationException: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50027: Invalid JWT token. No certificate thumbprint specified in token header.\r\nTrace ID: 9719e621-d8ef-4194-93cd-a78103d5df6b\r\nCorrelation ID: f0300795-fb99-44b2-bd95-8df3975290be\r\nTimestamp: 2016-08-29 13:51:26Z"}

I'm not sure how to pass thumbprint while calling acquireToken. Is anything missing here?

**Comment by fundamentalsguy** [comment]
Try using Tenant end point as https://login.microsoftonline.com/common/
Also does your resource need to be something other than vault.azure.net ? The client id (to which your certificate is associated in azure) must be granted access on the target resource.

An example below where I receive token for a shareoint site -
final static String AUTHORITY = "https://login.microsoftonline.com/common/";
final static String RESOURCE_ID = "https://your-target-site-domain/", //<<replace with your resource site domain >>

context = new AuthenticationContext(AUTHORITY, false, service);
            String keyFile = "C:\\Apps\\Aha\\bin\\Certificates\\XYZ.cer" ;
            String pkeyFile = "C:\\Apps\\Aha\\bin\\Certificates\\key.der" ;
            FileInputStream fis = null;
            ByteArrayInputStream bais = null;
            
             // use FileInputStream to read the file
             fis = new FileInputStream(keyFile);
             // read the bytes
             byte value[] = new byte[fis.available()];
             fis.read(value);
             fis.close();
             
             bais = new ByteArrayInputStream(value);
             
             // get X509 certificate factory
             CertificateFactory certFactory = CertificateFactory.getInstance("X.509");
              
             // certificate factory can now create the certificate 
             X509Certificate cert =  (X509Certificate)certFactory.generateCertificate(bais);            
            
             PrivateKey privateKey = getPrivateKey(pkeyFile);
            
            AsymmetricKeyCredential credential = AsymmetricKeyCredential.create(CLIENT_ID, privateKey, cert);
            Future<AuthenticationResult> future = context.acquireToken(RESOURCE_ID,credential,null);        
            result = future.get();

**Comment by kpanwar** [comment]
@yogeshronly4u - I was unable to repro your issue. Were you able to resolve it?

**Comment by SomkaPe** [comment]
Did not manage to reproduce, 
cert based access might not be configured correctly for  test application, 
Please have a look at https://blogs.msdn.microsoft.com/exchangedev/2015/01/21/building-daemon-or-service-apps-with-office-365-mail-calendar-and-contacts-apis-oauth2-client-credential-flow/
