### ISSUE TITLE
azure-activedirectory-library-for-java don't include the license file

### ISSUE THREAD

**Issue by puntogil** [AzureAD/azure-activedirectory-library-for-java#102]
Hi
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
Thanks in advance
Regards

**Comment by kpanwar** [comment]
We will add MIT license file

**Comment by brentschmaltz** [comment]
dup of: https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/116
