### ISSUE TITLE
Interactive Authentication for AAD native applications

### ISSUE THREAD

**Issue by devszr** [AzureAD/azure-activedirectory-library-for-java#105]
How does one go about presenting a consent dialog top the user in native interactive applications ? When using the .NET SDK, a browser window is automatically popped up asking for consent from the user of a new application. How do you get that to work when using ADAL4J ? I see that there is an issue and some commits here https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/73, but not sure what the status is ?

Until the Prompt Behavior is ported into ADAL4J, what options do I have to get my user to provide consent to the application ?

/Dev

**Comment by devszr** [comment]
Well, I was able to perform an out of band consent using the Oauth2 flow described at 
[https://azure.microsoft.com/en-us/documentation/articles/active-directory-protocols-oauth-code/]
Not sure if this the best way to do it though. Any best practices would be good information.

`https://login.microsoftonline.com/{tenant-id}/oauth2/authorize?client_id={client_id}&prompt=login&redirect_uri={redirect_uri}&response_type=code`

/Dev

**Comment by kpanwar** [comment]
there is no support for interactive auth in adal4j.

**Comment by nwarriorch** [comment]
Is there a plan to add interactive login support in adal4j any time soon ?

**Comment by kpanwar** [comment]
Not at the moment.
