### ISSUE TITLE
Multi Factor Authentication

### ISSUE THREAD

**Issue by umapriyadarsi** [AzureAD/azure-activedirectory-library-for-java#106]
I am not sure, if this is the best way to bring this issue up. For lack of a better forum, I am compelled to do so.

Does the ADAL4J support multi factor authentication? If so, how is this being done? The OAuth doc for Azure Graph Rest API does not talk at all about MFA : 
https://azure.microsoft.com/en-us/documentation/articles/active-directory-protocols-oauth-code/

Please help.

**Comment by psignoret** [comment]
If you are building a web application, then the fact that you are using ADAL4J is entirely irrelevant. During the authorization request, the user's browser will be directed to Azure AD. At that point the user will authenticate. This authentication may involve doing multi-factor authentication, which happens normally. After the user is authenticated, the user's browser will be redirected back to your web app, with the authorization code, which your app will exchange for an access token to whichever resource you requested access to in the first place (an example of such a resource would be the Azure AD Graph API, but it could also be a different resource).

In the diagram below, "Resource Owner" is the user, "User Agent" is the web browser, and "Client" is your web app. MFA happens during `(B) User authenticates`, and ADAL4J is a part of "Client", so it is not involved.

From https://tools.ietf.org/html/rfc6749#section-4.1:

```
     +----------+
     | Resource |
     |   Owner  |
     |          |
     +----------+
          ^
          |
         (B)
     +----|-----+          Client Identifier      +---------------+
     |         -+----(A)-- & Redirection URI ---->|               |
     |  User-   |                                 | Authorization |
     |  Agent  -+----(B)-- User authenticates --->|     Server    |
     |          |                                 |               |
     |         -+----(C)-- Authorization Code ---<|               |
     +-|----|---+                                 +---------------+
       |    |                                         ^      v
      (A)  (C)                                        |      |
       |    |                                         |      |
       ^    v                                         |      |
     +---------+                                      |      |
     |         |>---(D)-- Authorization Code ---------'      |
     |  Client |          & Redirection URI                  |
     |         |                                             |
     |         |<---(E)----- Access Token -------------------'
     +---------+       (w/ Optional Refresh Token)

   Note: The lines illustrating steps (A), (B), and (C) are broken into
   two parts as they pass through the user-agent.

                     Figure 3: Authorization Code Flow
```

If, however, you are building a native client application (i.e. not an application that runs in the browser), then you will have a difficult time, as ADAL4J does not currently support embedding a web browser component (the way ADAL for .NET does).

**Comment by umapriyadarsi** [comment]
We could use the web browser as our client. But the the thing is, we do not have a single cloud application to point the redirect_uri at. 

Our application will be deployed in multiple instances. 

So, for Azure ADs which have multi factor authentication, as far as I understand: 
1. either we have to create a new azure ad app for every instance of our product, or 
2. we will have to keep adding a new fqdn in the list of Reply urls(redirect_uri) for every instance deployment.

We are as of now using a single multi-tenant Azure Application to be used for the various installations of our product. 

Does this make sense? I hope I am able to communicate our scenario effectively. If not, please do let me know.

**Comment by brentschmaltz** [comment]
@umapriyadarsi MFA is opaque to ADAL4J.  The IdentityProvider (in this case AzureAD) controls the way authentication is satisfied. Do the different tenants have different MFA requirements?
