### ISSUE TITLE
Fails to create a AsymmetricKeyCredential from a windows store certificate

### ISSUE THREAD

**Issue by epot** [AzureAD/azure-activedirectory-library-for-java#110]
I am trying to use the following method "public static AsymmetricKeyCredential create(final String clientId, final PrivateKey key, final X509Certificate publicCertificate)" from a pfx certificate I installed manually in my Windows Store certificate. 
For that purpose, I am getting the certificate using the "SunMSCAPI" and the java.security.KeyStore package. However, I end up with the following exception thrown within the AsymmetricKeyCredential constructor:

> sun.security.mscapi.RSAPrivateKey`
cannot be cast to java.security.interfaces.RSAPrivateKey
java.lang.ClassCastException: sun.security.mscapi.RSAPrivateKey cannot be cast to java.security.interfaces.RSAPrivateKey
	at com.microsoft.aad.adal4j.AsymmetricKeyCredential.<init>(AsymmetricKeyCredential.java:74)
	at com.microsoft.aad.adal4j.AsymmetricKeyCredential.create(AsymmetricKeyCredential.java:173)

Is there any workaround this ?

**Comment by epot** [comment]
Here is a small reproducer.
In a WindowsStoreCertificateCredentials.java file:

`package awesome.keyvaulttest;

import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.util.Enumeration;

import com.microsoft.aad.adal4j.AsymmetricKeyCredential;
import com.microsoft.aad.adal4j.AuthenticationContext;
import com.microsoft.aad.adal4j.AuthenticationResult;
import com.microsoft.azure.keyvault.authentication.KeyVaultCredentials;
import org.apache.commons.codec.digest.DigestUtils;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class WindowsStoreCertificateCredentials extends KeyVaultCredentials {
    private String m_clientId = null;
    private String m_thumbprint = null;

    public WindowsStoreCertificateCredentials(String clientId, String thumbprint) {
        m_clientId = clientId;
        m_thumbprint = thumbprint;
    }

    protected AuthenticationResult getAuthResult(String authority, String resource) throws Exception {

        try {
            KeyStore keyStore = KeyStore.getInstance("Windows-MY", "SunMSCAPI");
            keyStore.load(null, null);

            Enumeration<String> aliases = keyStore.aliases();

            PrivateKey privateKey = null;
            X509Certificate certificate = null;

            while (aliases.hasMoreElements()) {
                String alias = aliases.nextElement();
                Certificate cert = keyStore.getCertificate(alias);
                if(cert instanceof X509Certificate) {
                    if(DigestUtils.sha1Hex(cert.getEncoded()).toLowerCase().equals(m_thumbprint.toLowerCase())) {
                        certificate = (X509Certificate)cert;
                        privateKey = (PrivateKey)keyStore.getKey(alias, "".toCharArray());
                    }
                }
            }
            if(privateKey == null || certificate == null) {
                throw new Exception("cannot find certificate...");
            }

            ExecutorService service = Executors.newFixedThreadPool(1);
            AuthenticationContext context = new AuthenticationContext(authority, false, service);
            AsymmetricKeyCredential certificateCredentials = AsymmetricKeyCredential.create(
                    m_clientId, privateKey, certificate);

            return context.acquireToken(resource, certificateCredentials, null).get();

        } catch (Exception e) {
            e.printStackTrace(System.out);
            throw new Exception("aaaaaaaaaaarglll");
        }
    }

    public String doAuthenticate(String authorization, String resource, String scope) {
        try {
            return getAuthResult(authorization, resource).getAccessToken();
        } catch (Exception e) {
            return "";
        }
    }
}`

And in a test file:
`package awesome.keyvaulttest;

import com.microsoft.azure.keyvault.KeyVaultClient;
import org.junit.Test;

public class HelperTest {
    @Test
    public void testKeyVault() throws Exception {
        KeyVaultClient client = new KeyVaultClient(new WindowsStoreCertificateCredentials(
                <put an Azure application id here>,
                <put a certificate thumbprinf of something available in your user account certificate store>
        ));

        String gna = client.getSecret(<put a keyvault secret id>).value();
        System.out.println(gna);
    }
}`

Dependencies needed:
`    testCompile group: 'junit', name: 'junit', version: '4.11'
    compile group: 'com.microsoft.azure', name: 'azure-keyvault', version: '1.0.0-beta3'
    compile group: 'com.microsoft.azure', name: 'adal4j', version: '1.1.3'
    compile group: 'commons-codec', name: 'commons-codec', version: '1.10'`

**Comment by epot** [comment]
To give some details, it seems the AsymmetricKeyCredential  constructor is doing an unsafe cast, and in my case it is not easy to work around it since the object I am actually passing is private (sun.security.mscapi.RSAPrivateKey).

**Comment by epot** [comment]
Ping ?

**Comment by kpanwar** [comment]
This change will not cause a breaking change to the API, but it should fail the signing as the API below we use for signing requires RSAPrivateKey.
http://static.javadoc.io/com.nimbusds/nimbus-jose-jwt/2.21/com/nimbusds/jose/crypto/RSASSASigner.html

Changing the surface would result in an exception at a later point in the source code.

**Comment by SomkaPe** [comment]
That link is pointing to 2.21 version, 
we uses com.nimbusds.nimbus-jose-jwt [4.16,)  - dependency of com.nimbusds.oauth2-oidc-sdk.5.8.1

it has  (PrivateKey privateKey) constructor :

https://bitbucket.org/connect2id/nimbus-jose-jwt/src/c17067f1b75dbd6d112c4462daedbec19b948ea7/src/main/java/com/nimbusds/jose/crypto/RSASSASigner.java?at=4.34.1&fileviewer=file-view-default

**Comment by quartelh** [comment]
Any resolution for this? 
I also run into this with a Java implementation accessing Azure key vault
