### ISSUE TITLE
Missing API call for acquireTokenUsingRefreshToken(string clientId, string resource) from Java ADAL 

### ISSUE THREAD

**Issue by Nisha2015** [AzureAD/azure-activedirectory-library-for-java#112]
We have a Java Web Service and we need to protect it via AAD.

We are trying to have Web API receive an access token from a native app, and then the API would be executing On-Behalf-Of flow to get access tokens for another resource. https://docs.microsoft.com/en-us/azure/active-directory/active-directory-authentication-scenarios#daemon-or-server-application-to-web-api

However since we don't have an API call for acquireTokenUsingRefreshToken(string clientId, string resource), we aren't able to implement this scenario and make use of the Refresh Token. 

Currently, there is no way in ADAL Java to use refresh token and get a new access token. Please look at code in AuthenticationContext.java.

Please get this functionality at the earliest.

**Comment by jianghaolu** [comment]
I dug around a little bit and found out that this was added in https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/17 but the changes got lost when `dev` branch was merged into `master`.

**Comment by jianghaolu** [comment]
Created a PR: https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/119. Owners of the project, please let me know if there's anything is missing.
