### ISSUE TITLE
Id Token is not signed

### ISSUE THREAD

**Issue by csikosbalint** [AzureAD/azure-activedirectory-library-for-java#117]
I am using this library sample (PublicClient.java) with Native application client_id. When I call .getIdToken() on the result object I receive an ID token without signature. Why is it not signed?

**Comment by brentschmaltz** [comment]
@csikosbalint who is creating the token?

**Comment by kpanwar** [comment]
ID Token is only used for metadata in ADAL. ID Token meant for the client application and ADAL does not support token validation because ADAL is an authentication library and not token validation library. Think of it as a conduit between the client application and resource. It would be poor security practice to consume a signed token but not validate it.

**Comment by brentschmaltz** [comment]
@kpanwar where does the token come from?

**Comment by psignoret** [comment]
To add to the response from @kpanwar, a couple things to keep in mind:

* In that sample, the ID Token is obtained through direct communication between the client (the native client app using ADAL) and the Token Endpoint (Azure AD), so the integrity of the ID Token is inherited from the channel's TLS (i.e. the fact that ADAL uses HTTPS to communicate with Azure AD to obtain the token).
* The ID Token is not intended to be used anywhere other than in the client which obtained it (i.e. your app). (You should not be passing the ID Token to other services (that's what Access Token is for).)

**Comment by psignoret** [comment]
@brentschmaltz Token is coming from Azure AD. Azure AD does not sign ID Tokens issued to public clients via Resource Owner Password Credentials grant flow (even if `scope=openid` is used in the token request).

**Comment by brentschmaltz** [comment]
@psignoret thanks for the explanation. From what I read, the ROPC grant returns an access_token. Is that what AAD does? Is there any POP between the user of the token and the resource provider?

**Comment by psignoret** [comment]
@brentschmaltz In ROPC, Azure AD returns a signed Access Token (AT) for the specified resource, a Refresh Token (RT), and an unsigned ID Token.

PoP of what, in your question? That the user presenting the AT is the same user to whom the AT was originally granted? There's nothing binding the AT to the user or the client, if that's what you mean. If the AT we misplaced, stolen or intercepted, it could be replayed against the resource server for as long as it is valid (1 hour, default).

**Comment by brentschmaltz** [comment]
@psignoret  OK, this is the id_token that arrives with the AT. That answers my original question - where did the id_token come from. 
The id_token is simply info for the client and is never used to communicate with any other service.

**Comment by csikosbalint** [comment]
Does this mean that I should open an issue for signed id_tokens (with WebApp client_id)?

**Comment by psignoret** [comment]
Can you elaborate on why you require the ID Token to be signed?

**Comment by mozowski** [comment]
Hi @psignoret is above information helpful? I can provide you with more details.

**Comment by brentschmaltz** [comment]
@mozowski @feelgoodman these id_tokens are arriving as an artifact of an OAuth request that returns an access_token. These id_tokens do not have to be signed. 
id_token flows are not designed to be shared among applications, they are used to provide identity artifacts.
The purpose of access_tokens, where the caller is asking for access to a restricted resource. On behalf of flows can be used to obtain access_tokens that contain the identity of the user.

**Comment by mozowski** [comment]
@brentschmaltz Thank you! So do you know how to obtain OpenID Connect token than can be used in 3rd Party applications using non interactive flow with Azure AD like described here: https://docs.aws.amazon.com/cognito/latest/developerguide/open-id.html ?
OpenID spec: https://openid.net/specs/openid-connect-core-1_0.html

**Comment by PhlashGBG** [comment]
Similar issue here, wanting to use a signed id_token as a federated identity assertion from our customer's AzureAD (or other IdP) into our application platform, where /we/ perform the authorisation of the asserted identity to access our stuff (ie: we check against what they have purchased). Given the documentation here (https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-id-and-access-tokens) very clearly states 'id_tokens are signed but not encrypted', I'm a bit confused as to why AzureAD chooses not to sign them in all circumstances?

Right now our customers are going to have to bodge this with access_tokens unless they are using Google or Salesforce who seem to sign their id_tokens, and as has been noted above, is also what AWS Cognito expects when acting as an authorisation hub.

**Comment by muei** [comment]
@mozowski Hey, I have the same issue with you, are you solved the connection between azure and the aws cagnito with oidc?

**Comment by mozowski** [comment]
@muei I have abandoned this project. I did not find a solution for that.

**Comment by muei** [comment]
@mozowski Yes, there is just one way to use SAML.

**Comment by alexeyvino** [comment]
I suspect ID token loses signature when refresh of access token happens. This is what I observe. Straight after authentication it's all right with proper signature but after refresh of access token the id token is also refreshed and the new one doesn't seem to have a signature.
