### ISSUE TITLE
Authenticate guest users invited into Azure AD

### ISSUE THREAD

**Issue by adarshrhegde** [AzureAD/azure-activedirectory-library-for-java#120]
I am trying to authenticate users in my web application using Azure AD to store user records. For authenticating the user I am using the AuthenticationContext.acquireToken() method to acquire the token. This is working for local users in my directory but not for guest users invited to the directory.

While authenticating guest users I am getting an error : "To sign into this application the account must be added to the directory" . However, I am sure the user has been successfully added to the directory as seen through the Azure Portal. Also, I have verified the same using the graph API where I can see the guest users in the user list in the directory.

So the question is how do I authenticate the guest user in my web application through code (not through redirecting to the Azure UI)?

EDIT:
I also get a debug level log saying "MexParser:80 - No matching policies" . This log is in MexParser.java however I have no clue what is causing this.

**Comment by psignoret** [comment]
Can you provide more details on which method overload for `acquireToken()` you're using? (I.e. what parameters are you passing in?)

**Comment by adarsh2570** [comment]
The method overload for acquireToken() being used is :
 public Future<AuthenticationResult> acquireToken(final String resource,
                                                     final String clientId, final String username,
                                                     final String password, final AuthenticationCallback callback)

This is my code that does the job of authentication:

 private static AuthenticationResult getAccessTokenFromUserCredentials(
    String username, String password) throws Exception {
    AuthenticationContext context = null;
    AuthenticationResult result = null;
    ExecutorService service = null;
    try {
         service = Executors.newFixedThreadPool(1);
         context = new AuthenticationContext("https://login.windows.net/<tenant_name>", false, service);
         Future<AuthenticationResult> future = context.acquireToken(
            "https://graph.windows.net", CLIENT_ID, username, password,
            null);
         result = future.get();
     } catch(Exception e){
        e.printStackTrace();
     } finally {
         service.shutdown();
     }

     if (result == null) {
         throw new ServiceUnavailableException(
                 "authentication result was null");
     }
     return result;
 }

**Comment by zhangzhang** [comment]
I got the same issue, I was trying the PublicClient example, I changed the URL and the client Id, after I input my username/password, I got a NullPointerException.
When I trace down to the code, I found the policy is read from an XML in URL:https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml
But in this XML, there is no policies section, so the I got an error message says: 
No matching policies
Then the BindingPolicy object returned by MexParser.getWsTrustEndpointFromMexResponse is null, caused the following exception, did microsoft changed the format of FederationMetadata recently?

log4j:WARN No appenders could be found for logger (com.microsoft.aad.adal4j.UserDiscoveryRequest).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at PublicClient.getAccessTokenFromUserCredentials(PublicClient.java:47)
	at PublicClient.main(PublicClient.java:28)
Caused by: java.lang.NullPointerException
	at com.microsoft.aad.adal4j.WSTrustRequest.execute(WSTrustRequest.java:68)
	at com.microsoft.aad.adal4j.AuthenticationContext.processPasswordGrant(AuthenticationContext.java:839)
	at com.microsoft.aad.adal4j.AuthenticationContext.access$0(AuthenticationContext.java:825)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:171)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" javax.naming.ServiceUnavailableException: authentication result was null
	at PublicClient.getAccessTokenFromUserCredentials(PublicClient.java:55)
	at PublicClient.main(PublicClient.java:28)

**Comment by adarsh2570** [comment]
I found out that authentication for guest users will only work if these users have been invited from some other Azure AD tenant. In my case I am able to authenticate the users invited from other tenants but the same is not working for my gmail account which is not a part of any Azure AD tenant. 

That means there are 2 types of guest users : i) imported from another tenant ii) not present in any tenant and directly added to your tenant.

The error described by zhangzhang is the same that I get while authenticating my gmail guest account.

**Comment by zhangzhang** [comment]
Thank you for the comment, adarsh2570, I'm still having that issue, the user I'm using is the Global Administrator of the Azure AD, and I created another user, both of them are not working. I don't know how to import an user from another tenant, I have only one tenant.

**Comment by zhangzhang** [comment]
followed the comment from adarsh2570, I found out that Azure AD supports two types of users, one is called Microsoft Account, another is Microsoft Azure Active Directory, the example code PublicClient only works with the Microsoft Azure Active Directory account, this type of account normally has a suffix of your domain.

**Comment by adarsh2570** [comment]
zhangzhang you are right. Only thing that I would like to correct is the Microsoft Azure Active Directory account need not specifically have the suffix of your domain only. If the account belongs to some other Microsoft Azure Active Directory and you have invited it to your directory then it will have a different suffix. 

Regarding your earlier comment on importing users from another tenant, you can do that from your Azure UI. You add guest users in the same way you add local users. An invite email will go to them and once they accept the invite they will be visible in your tenant. These users will get authenticated from the PublicClient code.

**Comment by zhangzhang** [comment]
Thank you adarsh2570.

**Comment by raman1901** [comment]
Hi @adarsh2570 and @zhangzhang 

Did you guys find any way to authenticate this 2nd type of users - "not present in any tenant and directly added to your tenant"

**Comment by dcapslock** [comment]
+1 to fix this. I believe Atlassian Crowd uses this code and as such Guests do not working with their Azure AD plugin.

**Comment by psignoret** [comment]
@dcapslock Can you clarify which method of this library Atlassian Crowd is using?

**Comment by alexvanvucht** [comment]
@psignoret Latest Atlassian Crowd 3.3.2 loads this library: adal4j-1.2.0.jar

**Comment by sangonzal** [comment]
ADAL4J is in maintenance mode and no new features will be added going forward except for security fixes. All ongoing efforts will be focused on improving [MSAL4J](https://github.com/AzureAD/microsoft-authentication-library-for-java).

If you run into this issue with MSAL4J, please open an issue.
