### ISSUE TITLE
Add support for V2 of Micosoft Azure API 

### ISSUE THREAD

**Issue by matiman** [AzureAD/azure-activedirectory-library-for-java#125]
Currently adal4j only works for v1 in order to retrieve auth code and token but that doesn't work for v2.

**Comment by kriede** [comment]
I do very much appreciate having this Issue implemented.

**Comment by coyote1980** [comment]
I would like to raise my hand, having V2 implemented would be highly appreciated!

**Comment by sangonzal** [comment]
Hi @matiman , @kriede, @coyote1980 we now [MSAL for Java](https://github.com/AzureAD/microsoft-authentication-library-for-java), which works with the v2 endpoint. Happy to help with any questions/problems that you might run into as you get acquainted with MSAL
