### ISSUE TITLE
Expand Resiliency Error Codes

### ISSUE THREAD

**Issue by kgidewall** [AzureAD/azure-activedirectory-library-for-java#127]
We currently invoke resiliency mode when the following conditions occur: network timeout or http error codes 500, 503, 504. After discussion, we have decided to expand the error code list to include ALL http error codes 500 - 599. Please change your logic to include all of those codes for Resiliency.

**Comment by SomkaPe** [comment]
Resiliency is not implemented yet,  labeling as Enhancement

**Comment by sangonzal** [comment]
ADAL4J is in maintenance mode and no new features will be added going forward except for security fixes. All our ongoing efforts will be focused on improving MSAL4J.
