### ISSUE TITLE
Allow the Http Handler to be specified

### ISSUE THREAD

**Issue by stfkbf** [AzureAD/azure-activedirectory-library-for-java#134]
Apologies if this has been considered already.

When using this library to authenticate inside a Weblogic server, it will fail due to URL.openConnection not returning a HttpsURLConnection. The work around is to set:

-DUseSunHttpHandler=true

Alternatively when creating URL obejcts (which is done only a few places in the adal4j code), they could be created as follows:

new URL(null, this.getAuthority(), new sun.net.www.protocol.https.Handler())

This would alleviate the need to set this at the server level. Perhaps the HttpHandler (URLStreamHandler) could be set in a manner similar to the Proxy?

Many thanks.

**Comment by aybkira** [comment]
Hi , 

I Have a same problem  , can you tell me if you have find the solution ?

**Comment by stfkbf** [comment]
Hello,

One option is to set -DUseSunHttpHandler=true when starting the app server. This changes the behaviour for the entire app server or cluster (may not be desirable if you have several applications running). Alternatively there are about four or five places in the code in the HttpHelper and AuthenticationConext classes where URLs are created. These can be changed to create the URL as follows:

new URL(null, <URL>, new sun.net.www.protocol.https.Handler())

This approach does mean including the adal4j source code in your application though. Hence the question if this could become a property similar to the way the proxy works.

**Comment by manikandanramaswami** [comment]
I am getting this issue when ADAL4J is used by MSSQL-JDBC 7.4.0 driver under Cold Fusion 11 Environment. This enhancement is much needed for me. I made it work successfully by adding `new URL(null, <URL>, new sun.net.www.protocol.https.Handler())` and recompiling ADAL4J
Adding `-DUseSunHttpHandler=true` in Cold Fusion JVM arguments didn't make any difference unfortunately.

**Comment by sangonzal** [comment]
@manikandanramaswami ADAL is now in maintenance mode, and we will only release new versions for security fixes. Have you considered using [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-java)? As of version 1.1.0, MSAL allows for configuring of Http Client. Here is the [wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Configure-Http-Client) explaining how to do so.
