### ISSUE TITLE
Ability to pass a client secret for username/password based authorization

### ISSUE THREAD

**Issue by praneetloke** [AzureAD/azure-activedirectory-library-for-java#144]
While trying to retrieve an access token using the username/password combination, I discovered that this would only work if the client ID is configured as a Native App since they are considered to be "public" clients as opposed to web apps/APIs being "confidential" clients. But my situation requires me to request a token for a *web app* using the username/password for a user in the AD.

The specific error that prevents me from using the username/password variant for a non-native app client ID:

```
{
  "error": "invalid_client",
  "error_description": "AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: d6a115a7-3a2c-4296-8d5b-90fa21fe1900\r\nCorrelation ID: 95eee7ee-8dd0-44a8-a93a-53d9f9f07cd7\r\nTimestamp: 2017-05-08 01:08:11Z",
  "error_codes": [
    70002
  ],
  "timestamp": "2017-05-08 01:08:11Z",
  "trace_id": "d6a115a7-3a2c-4296-8d5b-90fa21fe1900",
  "correlation_id": "95eee7ee-8dd0-44a8-a93a-53d9f9f07cd7"
}
```

In order to correct that error and pass the 'client_secret' as well along with the username/password in the POST request, I am currently making a manual POST request to the AAD authorization endpoint outside this library. It works but I don't want to do that. I want to use the library to do this.

I also tried to extend the `AuthenticationContext` class to do this myself but then the `acquireTokenCommon` method takes a concrete type `AdalAuthorizatonGrant`, which by the way has a typo in the class name. I am not sure if there is currently a way to pass additional parameters through some callback/hook? If not, can you please:
- add an extension method, which would allow users to pass the `client_secret` as well for non-native apps along with the username/password
- or, introduce an interface for the `AdalAuthorizationGrant` and thus allowing us to extend the `AuthenticationContext` for scenarios where we have to send additional parameters.

I'd be happy to submit a PR for this if you let me know what your preferred way of handling this is.

**Comment by psignoret** [comment]
The only supported use of username/password is with apps registered as public clients (i.e. native client applications). You *must not* make these requests for confidential clients, as that is unsupported and the service will stop accepting those requests at any moment.

See also why #100 was closed.

**Comment by praneetloke** [comment]
@psignoret I wasn't aware that it is unsupported and that the service will soon stop accepting those requests. Is there an official announcement about this and when this would actually stop working? Having said that, it doesn't seem like it is worth doing what I proposed in my first comment in this issue. I'll close this for now.

**Comment by psignoret** [comment]
@praneetloke It has never been supported, so there has not been any announcement. To my knowledge, we have never stated that the username/password flow (the OAuth 2.0 Resource Owner Password Credential Grant flow, to be specific) is a supported flow in Azure AD for anything other than native client applications (and even for native client apps, we try to make it quite clear that it is strongly discouraged).

The ADAL libraries which have implemented this flow, only do so for native client applications (public clients), never for web apps (confidential clients).

In either case, it would appear that an official article in the docs is in order, articulating why the flow is discouraged, when it is supported and when it is not. I'll follow up with our team and see to getting this done soon.

**Comment by praneetloke** [comment]
@psignoret what you say makes sense. While there may not be an explicit article stating that the username/password with the client_secret is supported by the AD service, the fact that the service responds with an error expecting a client_secret or assertion for non-native client ID is a bit misleading. This is probably why many of us are trying to use it. At least, that is why I am trying to use it (and in fact I do). But because you say that it can stop working anytime, I am going to move away from it and advice our cloud-ops about creating native apps if username/password resource owner authorization flow is needed.

**Comment by wobba** [comment]
I know this is an old one. My scenario is calling an endpoint which don't allow app tokens, while all other endpoints support it. As I'm using app tokens, I only want to use username/pw for certain resources.

While `authenticationContext.AcquireTokenAsync(GraphResourceId, _appId, userPasswordCredential);` generates the AADSTS70002 error, tacking on the adal app secret on the payload to `https://login.windows.net/tenant.onmicrosoft.com/oauth2/token` does yield a valid delegated token. 

Even though you say it's unsupported, it does indeed work, and seems overkill to have to create two separate ADAL apps to support this, one native and one web/api.

**Comment by psignoret** [comment]
@wobba Regardless of whether or not it works today, this functionality is undocumented, explicitly unsupported, and against Microsoft's recommendation. It will not be added to this library.

**Comment by wobba** [comment]
@psignoret No problem, and just one of those roadblocks we tend to hit every time we try to create solutions :) If the call itself is unsupported as well (not just in the lib), I'd prefer the call to fail - not tempting  developers to work around something which was never intended.

**Comment by potaty** [comment]
Bad documents. I waste a few hours on this feature.
