### ISSUE TITLE
Authority URL is getting truncated

### ISSUE THREAD

**Issue by kollud** [AzureAD/azure-activedirectory-library-for-java#145]
Hi,
We need to go through data power gateway to communicate with external providers.

Our data power team has provided url for authority as https://xxx.corp.com/api/CRMWebAPIService/v1/Common/ to connect to Microsoft authority url https://login.microsoftonline.com/common/.

But adal4j.jar provided by Microsoft is truncating this part api/CRMWebAPIService/v1/Common/ and invoking services as https://xxx.corp.com/common/userrealm/abc@abc.com?api-version=1.0 , due to which request is not reaching data power.

Is it possible to provide fix which takes complete URL and appends required extra parameters.

Thanks,
Durga

**Comment by SomkaPe** [comment]
ADAL Java does not support Authority in the mentioned form. Only first segment in the path is taken to account, which should  be "adfs" if it is ADFS authority or it will be treated as AAD Tenant otherwise.

**Comment by psignoret** [comment]
@kollud Are you sure that `https://xxx.corp.com/api/CRMWebAPIService/v1/Common/` is the URL for the _authority_, and not the URL for the _resource_ (i.e. the endpoint for which you will get an access token, not the endpoint _providing_ the access token)? 

If this is a resource expecting an access token from Azure AD, you authority is most likely either `https://login.microsoftonline.com/common/` or `https://login.microsoftonline.com/<your tenant ID or domain name>/`.
