### ISSUE TITLE
Integrated auth support for Java sdk

### ISSUE THREAD

**Issue by saurabh500** [AzureAD/azure-activedirectory-library-for-java#149]
Is integrated auth supported with the java SDK?
I see that dotnet SDK for adal support the functionality. 
I see that it is possible with Java as well. Is the feature in the pipeline? If not on the roadmap of the team then would you be willing to accept a PR for this feature? 
Context: we need this capability from adaj4j so that we can support integrated auth in our mssql jdbc driver to authenticate with Azure Sql db using AAD.

**Comment by kpanwar** [comment]
it is already supported. https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/main/java/com/microsoft/aad/adal4j/AuthenticationContext.java#L229
if the user is federated, adal would attempt ws-trust flow.

**Comment by v-xiangs** [comment]
hello @kpanwar we looked at the method you point out, but seems like it requires username and password to authenticate. Therefore, I believe the method is not for integrated authentication. Do you know if there is any other methods I can use for integrated authentication (without username and password). Thank you.

**Comment by saurabh500** [comment]
@kpanwar The link to code you have provided, validates that the username and password has been supplied. The requirement is to be able to use authentication without specifying the username and password. Can this issue be reopened and tracked?
