### ISSUE TITLE
Are Client_ID and username the same?

### ISSUE THREAD

**Issue by ilyauts** [AzureAD/azure-activedirectory-library-for-java#154]
When using an application id for a username and the application key for the password, are the username and client_id fields the same in the sample code?

**Comment by SomkaPe** [comment]
Could you please provide details about your case?

**Comment by psignoret** [comment]
@ilyauts If you are referring to the [public client]() sample, where this method signature is used:

```java
Future<AuthenticationResult> future = 
    context.acquireToken(RESOURCE, CLIENT_ID, username, password, null);
```

Then no, the client ID and app secret are not the username and password, respectively. That signature above is used to authenticate a *user* with their username/password.

To obtain an access token in the context of an *application* using the client ID and client secret, you would use something along the lines of the following, which invokes the [client credentials]() grant flow:

```java
ClientCredential credential = new ClientCredential(CLIENT_ID, CLIENT_SECRET);
Future<AuthenticationResult> future = 
    context.acquireToken(RESOURCE, clientCredential, null);

```

**Comment by ilyauts** [comment]
Thanks for your help, we were using the wrong Java SDK, it has since been resolved.
