### ISSUE TITLE
AuthenticationContext should provide the function to set the proxy credential

### ISSUE THREAD

**Issue by logikeer** [AzureAD/azure-activedirectory-library-for-java#155]
There are many proxy setting in our product. Azure cloud is one of them.
The adal4j should provide the function to set the proxy credential, and not to use the properties in JVM.

AWS SDK and vCloud SDK have the similar function to set the proxy credential.

**Comment by kpanwar** [comment]
It already does. https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/main/java/com/microsoft/aad/adal4j/AuthenticationContext.java#L127

**Comment by logikeer** [comment]
I know there is the function to set the proxy including URL and port.
But it can not set the credential for the proxy, like the username and password for the proxy auth.

**Comment by jianghaolu** [comment]
+1

**Comment by dtretyakov** [comment]
It is a blocker since Azure SDK for Java depends on it: https://github.com/Azure/azure-sdk-for-java/pull/1787#discussion_r132246986

**Comment by dtretyakov** [comment]
Note: take into account that in java sdk to provide credentials used [Authenticator](https://square.github.io/okhttp/3.x/okhttp/okhttp3/Authenticator.html) from okhttp3 library.
It seems that you could also switch from `HttpsURLConnection`-related stuff to it.

**Comment by SomkaPe** [comment]
Proxy authentication can be set by using java.net.Authenticator 
Example:

    Authenticator.setDefault(new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication("login", "password".toCharArray());
        }
    });

**Comment by logikeer** [comment]
This method will impact all cloud connections. I want only to setup the proxy credential on the cloud connection for Azure, not other cloud connections.

**Comment by SomkaPe** [comment]
In order to that you need to configure AuthenticationContext with  SSLSocketFactory instance for creation of tunneling sockets.  Example -  https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/167

**Comment by navyasric** [comment]
Closing this as the sample above was merged to 1.3.0 release

**Comment by dtretyakov** [comment]
@jianghaolu, will you reuse approach suggested by this team in the azure-sdk-for-java?

**Comment by dspurling** [comment]
When providing an SSLTunnelSocketFactory to the AuthenticationContext the createSocket methods of the SSLTunnelSocketFactory are never called.
