### ISSUE TITLE
Microsoft Graph or Azure AD Graph

### ISSUE THREAD

**Issue by mores** [AzureAD/azure-activedirectory-library-for-java#164]
It seems like the examples you provide:
https://github.com/Azure-Samples/active-directory-java-native-headless utilize the Azure AD Graph (graph.windows.net).

According to: https://blogs.msdn.microsoft.com/aadgraphteam/2016/07/08/microsoft-graph-or-azure-ad-graph/  New applications should use  Microsoft Graph (graph.microsoft.com).

Can adal4j be used with Microsoft Graph ?
If so, is there an example/doc ?
If not, is there an alternate project to get those access tokens ?

**Comment by navyasric** [comment]
Closing this issue as the question seems to be answered

**Comment by alexis-puska** [comment]
And how can i get the token for microsoft graph with the add-in tocken ?

I used the code generate to create a addins for office 365 and with the javascript function getAccessTokenAsync whe get an addins token. source : 
https://docs.microsoft.com/fr-fr/office/dev/add-ins/develop/sso-in-office-add-ins

with Adal4j i try to get the graph ampi with this addin token but i only get error code: 
"error_description":"AADSTS50013: Assertion contains an invalid signature. [Reason - The key was not found...

 

final ClientCredential credential = new ClientCredential("application id",
                "secret generated with password in azure application configuration");
        final UserAssertion assertion = new UserAssertion(idToken);

        AuthenticationResult result = null;
        ExecutorService service = null;
        try {
            service = Executors.newFixedThreadPool(1);
            String tenantId = /* tenant of my azure instance */;

            final AuthenticationContext context = new AuthenticationContext(
                    "https://login.microsoftonline.com/" + tenantId + "/", false, service);
            
            final Future<AuthenticationResult> future = context.acquireToken("https://graph.windows.net/", assertion, credential, null);
