### ISSUE TITLE
Cannot get Authentication Token using Refresh token with username and password 

### ISSUE THREAD

**Issue by tanimak** [AzureAD/azure-activedirectory-library-for-java#165]
Why there are no methods supporting refreshing the access token using refresh token, when using username and password. 

I have asked the detailed question in, 
https://stackoverflow.com/questions/45694705/adal4j-java-use-refresh-token-with-username-and-password-to-get-the-access-tok

Are there any limitations in java version? 

Thank You.

**Comment by sangonzal** [comment]
@tanimak Sorry for the delay in response. ADAL4J has added support for acquiring an access token using a refresh token. Take a look at any of the overrides for acquireTokenByRefreshToken
