### ISSUE TITLE
AuthenticationResult.expiresOn is actually expiresIn

### ISSUE THREAD

**Issue by nwoolls** [AzureAD/azure-activedirectory-library-for-java#18]
Tough to say if this is truly a bug but I'd like an idea so I can either work with the current implementation of submit a PR.

The value of expiresOn is actually the number of seconds the token expires**In**. In the .NET version of the Azure AD auth code, expiresOn is the DateTime that the token will expire, calculated using the expires_in value from the response.

**Comment by nwoolls** [comment]
After thinking a bit more on it, this is what I would propose:

```
    @Deprecated
    public long getExpiresOn() {
        return expiresIn;
    }

    public long getExpiresAfter() {
        return expiresIn;
    }

    public Date getExpiresOnDate() {
        return expiresOn;
    }
```

If that concept seems sound I will submit the PR. Thanks for your consideration.

**Comment by nwoolls** [comment]
FWIW I submitted a PR for this after finding this had already introduced what looks like a logic bug in the Web App sample.

**Comment by brandwe** [comment]
@kpanwar to triage. @nwoolls if you can, can you link to the PR here just so we know all the threads that wrap up in to this PR? Thanks!

**Comment by brandwe** [comment]
Never mind - found it - #19

**Comment by samjamesobrien** [comment]
Just came across this issue myself, I see the fix was merged, but do you plan on doing a new release with the fix on maven?

If not I will have to include a snapshot version in our own private nexus,

Thanks

**Comment by MikeN123** [comment]
As the PR fixing this has been merged, close the issue?
