### ISSUE TITLE
Cannot be used in Android environment because of commons-codec-1.3 compatibility

### ISSUE THREAD

**Issue by james-hu** [AzureAD/azure-activedirectory-library-for-java#180]
In Android environment, commons-codec-1.3 is embedded in the OS, there is no way to change it or bring your own version of that library.

Base64.encodeBase64(...) method used in azure-activedirectory-library-for-java does not exist in commons-codec-1.3, therefore, azure-activedirectory-library-for-java cannot be used in Android environment.

The fix is simple, just modify AuthenticationContext.java, replace lines like "Base64.encodeBase64String(response.getToken().getBytes())" with "new String(Base64.encodeBase64(response.getToken().getBytes()))", and replace lines like "Base64.encodeBase64URLSafeString(hash)" with "new String(Base64.encodeBase64((hash))).repleace('+', '-').replace('/', '_')"

Pull request is here: https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/181

**Comment by psignoret** [comment]
If you're developing for Android, have you considered using https://github.com/AzureAD/azure-activedirectory-library-for-android instead?

**Comment by james-hu** [comment]
I've looked into that "for-android" library before. That library depends on Android environment so it cannot be used in plain Java 7/8/9 environment. What I need is something that can be used in both Java 7/8/9 and Android. The pull request contains only 3 changes in a single file, and it works for me in both Java 7/8 environment and Android environment in my work projects.

**Comment by james-hu** [comment]
any interest to merge my pull request?
