### ISSUE TITLE
AuthenticationCallback.onFailure() should be invoked with the actual exception (ExecutionException.getCause())

### ISSUE THREAD

**Issue by SreeramGarlapati** [AzureAD/azure-activedirectory-library-for-java#186]
To Repro:
Create `AuthenticationContext` with invalid `tenant` and then invoke `acquireToken` call.

Expected:
`AuthenticationCallback.onFailure(Throwable throwable)` sees throwable is instance of `adal4j.AuthenticationException`.
Actual:
Throwable instance of `ExecutionException`

ExecutionException is an infrastructure related error; i.e., the API happened to run on an ExecutorService which caught & raised this exception, but, the getCause() is the actual error that happened - which is what is interesting for `AuthenticationCallback.onFailure` API.

**Comment by sangonzal** [comment]
@SreeramGarlapati ADAL4J is in maintenance mode and no new features will be added going forward except for security fixes. All our ongoing efforts will be focused on improving [MSAL4J](https://github.com/AzureAD/microsoft-authentication-library-for-java). If this is still of concern to you feel free to open an issue on the MSAL repository.
