### ISSUE TITLE
Port-over from Applications insights issue #361

### ISSUE THREAD

**Issue by Cpt-xx** [AzureAD/azure-activedirectory-library-for-java#188]
Referring to https://github.com/Microsoft/ApplicationInsights-Java/issues/361, and on suggestion of one of the people over there.

The text (in case the link would fail in the future):
===
We're having a hard time unit testing adal4j in isolation. The way the authentication needs to be set up (creating a new com.microsoft.aad.adal4j.AuthenticationContext) forces us to run unit tests in an environment where an active AAD needs to be present. This can be circumvented by using debatable products as PowerMock (intercepting the 'new' and allowing a replacement to be put into place). Also the use of final classes (such as com.microsoft.aad.adal4j.AuthenticationResult) forces the use of PowerMock.
We would rather not use PowerMock to run our unit tests, and would rather use a more controlled adal4j provided test framework, or use a adal4j provided factory.

If that factory were to be implementing an interface, that would make injecting the factory as a collaborator a neat pattern, allowing for easy and clear unit testing possible. Removing the final directive from the AuthenticationResult, replacing this with an interface and an actual implementing class (which can be made final if you should wish to) also makes for much easier unit testing without the use of PowerMock.

Are there any documents in place guiding us in creating isolated unit tests which would not require an active ActiveDirectory to be present?

---

Continuing:

===
In the meantime I have been using ADAL4J (yes, ADAL4J, not only the AuthenticationContext) and I've run in another couple of problems with unit testing.
Example:
KeyVaultClient.
KeyVaultClient is a class that is used, basically as an interface to the KeyVault. It translates java-invocations in Rest-interactions with the Azure Key Vault.

In order to use that you have to instantiate the KeyVaultClient with an authorisation token object.
So if I want to unit test the application facing class I hand it the mock of a token (I don't want to calculate a token for each unit test, why should I, that is done by classes that are not mine). But, wait... that will ask all kinds of questions to my token mock, because it wants to actually initialize the KeyVaultClient. And I can't guarantee that I have a KeyVault running in my unit test environment.
Solution: use a KeyVaultClient factory and have that factory return a mock KeyVaultClient in a unit test environment. That way I can precisely let the KeyVaultClient mock return whatever I want it to, without having to have a KeyVault infrastructure up and running.
But wait... I cannot use Mockito (a fairly standard tool for mocking classes) because KeyVaultClient is final, it can't be used by Mockito (and probably also not by EasyMock) to create a mock for, as you can't extend a final class.
So now I not only have to create KeyVaultClientFactory (which I had to do anyway) but now also I need to create a KeyVaultClientWrapper, which delegates the calls to the KeyVaultClient (inner class) and implement all methods that I use in my whole application so that I can mock the KeyVaultClient class (via the wrapper) and have the KeyVaultClientWrapper class returned from the KeyVaultClientFactory.

This is just one example, there are plenty more.
My suggestion would be for you to look at other frameworks such as java.security.* which uses interfaces extensively to communicate with the outside world and hides implementation details (such as a final class) from the outside world. This leaves open the possibility of creating mocks (as interfaces are easily and always mockable), but (and that is perhaps more compelling for you guys) also opens up the way for easy extension and replacement of implementations of these interfaces by your application.

---

Continuing:

===

Further suggestions:
In order for ADAL4J to be better mockable, I would suggest you replace the classes with interfaces (with the same name) and have the implementation be final. That way the interfaces can easily be mocked (interfaces are mockable by definition as they cannot be final). By using a factory class to obtain the implementation you open up the easy way of introducing better, other implementations which can be instantiated by using configuration files. That way we can inject a mock of the interface into the class which is under unit test and take away the dependency which we now have on an actual implementation running in the Unit test environment (which is the actual root of the problem here).

---

**Comment by sangonzal** [comment]
@Cpt-xx Thanks for the feedback/suggestions. We will take them into consideration as we work to release MSAL Java
