### ISSUE TITLE
AADSTS70000: Transmission data parser failure: Refresh Token is malformed or invalid error for refresh token

### ISSUE THREAD

**Issue by sivajiyerra** [AzureAD/azure-activedirectory-library-for-java#190]
I am trying to get the refresh token using the refresh token received from the access token API. But how many tried, it always return the malformed error.

I set the scope while sending the access token request. Please not that I am using generic HTTP requests from the JAVA. Please find the request I made and responses I received.

**Get Access Toke API:**
**URL: ** [https://login.microsoftonline.com/common/oauth2/v2.0/token](Get Token)
**Headers: **Authorization: Bearer code
**Post Data: **client_id=<My_Client_Id>&scope=offline_access%20calendars.readwrite&code=<Code_Received_From_Authorization>&redirect_uri=<My_URL>&grant_type=authorization_code&client_secret=<My_Secret>

**Response received is:**
{"token_type":"Bearer","scope":"Calendars.Read Calendars.ReadWrite Calendars.ReadWrite.Shared Mail.Read User.Read","expires_in":3599,"ext_expires_in":0,"access_token":"<Received_Token>","refresh_token":"<Received_Refresh_Token>"}

I am using the refresh token received in the above request to fetch the access code.

**Refresh Token API**
**URL: ** [https://login.windows.net/common/oauth2/token](Refresh Token)
**Headers: **Content-Type: application/x-www-form-urlencoded
**Post Data: ** client_id=<My_Client_Id>&refresh_token=<Token_Received>&client_secret=<My_Secret>&resource=https://outlook.office365.com&grant_type=refresh_token

With this request I am getting the following issue:

{
	"error": "invalid_grant",
	"error_description": "AADSTS70000: Transmission data parser failure: Refresh Token is malformed or invalid.\r\nTrace ID: 7a7f249d-be63-4de1-2oi6-eaa3277b4000\r\nCorrelation ID: f85ae2cc-85kl-482e-989L-cae30afdc293\r\nTimestamp: 2017-12-21 13:22:19Z",
	"error_codes": [
		70000
	],
	"timestamp": "2017-12-21 13:22:19Z",
	"trace_id": "7a7f249d-be63-4de1-2oi6-eaa3277b4000",
	"correlation_id": "f85ae2cc-85kl-482e-989L-cae30afdc293"
}

**Note: ** I am using raw HTTP calls, not the library.

Ref I followed: [https://blogs.msdn.microsoft.com/exchangedev/2014/03/25/using-oauth2-to-access-calendar-contact-and-mail-api-in-office-365-exchange-online/](MSDN)

**Comment by sangonzal** [comment]
@sivajiyerra Sorry for the delay in responding. The URL the reference doc that you posted is broken. If you would like to see an updated tutorial on how to acquire an access token using raw HTTP messages I'd recommend this [tutorial](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code)

For this specific case, it looks like you are requesting a token from the v2.0 endpoint, and then using the refresh token to acquire a token from v1.0 endpoint. The second URL should be https://login.windows.net/common/oauth2/v2.0/token
