### ISSUE TITLE
Get Microsoft graph token with adal4J and addin token ?

### ISSUE THREAD

**Issue by alexis-puska** [AzureAD/azure-activedirectory-library-for-java#208]
And how can i get the token for microsoft graph with the add-in tocken ?

I used the code generate to create a addins for office 365 and with the javascript function getAccessTokenAsync whe get an addins token. source :

        function getCallbackToken() {
            Office.context.mailbox.getCallbackTokenAsync(cbToken);
        }
  
        function cbToken(asyncResult) {
            var token = asyncResult.value;
            console.log('token : '+token);
        }

         function getIdentityToken() {
            Office.context.mailbox.getUserIdentityTokenAsync(cbIdentity);
          }
  
          function cbIdentity(asyncResult) {
            var identity = asyncResult.value;
            console.log('identity : '+identity);
          }

https://docs.microsoft.com/fr-fr/office/dev/add-ins/develop/sso-in-office-add-ins

with Adal4j i try to get the graph ampi with this addin token but i only get error code:
"error_description":"AADSTS50013: Assertion contains an invalid signature. [Reason - The key was not found...

    final ClientCredential credential = new ClientCredential("application id",
            "secret generated with password in azure application configuration");
    final UserAssertion assertion = new UserAssertion("tocken get from addin");

    AuthenticationResult result = null;
    ExecutorService service = null;
    try {
        service = Executors.newFixedThreadPool(1);
        String tenantId = /* tenant of my azure instance */;

        final AuthenticationContext context = new AuthenticationContext(
                "https://login.microsoftonline.com/" + tenantId + "/", false, service);
        
        final Future<AuthenticationResult> future = context.acquireToken("https://graph.windows.net/", assertion, credential, null);

**Comment by sangonzal** [comment]
@alexis-puska Based on the link that you have posted, it seems that Office Add-Ins that use the SSO API only work with the v2 endpoint. ADAL4J only supports the V1 endpoint (See [link](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-compare) for the differences in between v1 and v2)

**Comment by alexis-puska** [comment]
I have try to validate this token with a manually call to this url : 
https://login.microsoftonline.com:443/{tenantId}/oauth2/v2.0/token
With this parameters : 
client_id: app id declare inside Azure
client_secret : secret declare for the app inside azure
assertion : token obtain with javascript librarie inside the complement
scope  : https://graph.microsoft.com/user.read offline_access
requested_token_use :  on_behalf_of
grant_type : urn:ietf:params:oauth:grant-type:jwt-bearer
client_assertion_type : urn:ietf:params:oauth:client-assertion-type:jwt-bearer

response : 
{
"error": "invalid_grant",
"error_description": "AADSTS50013: Assertion contains an invalid signature. [Reason - The key was not found., Thumbprint of key used by client: '0600F9F674620737E73404E287C45A818CB7CEB8', Configured keys: [Key0:Start=05/11/2018, End=05/11/2020, Thumbprint=rtXeg2pR6Jdjtesg;Key1:Start=06/21/2018, End=06/21/2020, Thumbprint=v5KJ82o/0eMeBR2W;Key2:Start=11/16/2016, End=11/16/2018, Thumbprint=i1DVz66b9dfpPV3Z;]] Trace ID: f693d3cb-4d89-4c42-9818-5cc5689b8600 Correlation ID: 94f65f00-ce84-448b-ad5d-01bf0795f301 Timestamp: 2018-06-25 11:49:57Z",
"error_codes": [
  50013
],
"timestamp": "2018-06-25 11:49:57Z",
"trace_id": "f693d3cb-4d89-4c42-9818-5cc5689b8600",
"correlation_id": "94f65f00-ce84-448b-ad5d-01bf0795f301"
}


I really don't see where is the problem to validate this addin token.

The Oauth authentication mecanism, redirection to the login microsoft 365 page, after login redirect to the redirect url of the application, and get the token by graph api post in the applicatino work very well. Adal4j works...
