### ISSUE TITLE
AADSTS90013: Invalid input received from the user.  When password with &# is used

### ISSUE THREAD

**Issue by mpradny** [AzureAD/azure-activedirectory-library-for-java#212]
I found an issue when acquiring a token when password had **&#** inside. I used https://github.com/azure-samples/active-directory-java-native-headless sample and I always got   `com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS90013: Invalid input received from the user.` for my primary test account.

Code snippet from source:
```java
String password = "secure&#9pass";
service = Executors.newFixedThreadPool(1);
context = new AuthenticationContext(AUTHORITY, false, service);
Future<AuthenticationResult> future = context.acquireToken(
                    "https://graph.microsoft.com", CLIENT_ID, username, password,
                    null);
```

When I tried different account, everything worked fine. Also if I remove & or # from password, I get correct response that password is incorrect. When I do any other change in password, I get same Invalid input error message.

**Comment by sangonzal** [comment]
Fixed by the service
