### ISSUE TITLE
On-behalf-of flow support using AsymmetricKeyCredential (certificate based)

### ISSUE THREAD

**Issue by marcinzi** [AzureAD/azure-activedirectory-library-for-java#213]
I am missing a method to acquire access token on-behalf-of a user, where client authenticates with certificate. There is only support for this flow, where client authenticates with client secret:

existing:
public Future<AuthenticationResult> acquireToken(
 final String resource,
 final UserAssertion userAssertion, 
 final *ClientCredential* credential,
 final AuthenticationCallback callback) 
{ ... }

wanted:
public Future<AuthenticationResult> acquireToken(
  final String resource,
  final UserAssertion userAssertion,
  final **AsymmetricKeyCredential** credential,
  final AuthenticationCallback callback) 
{...}

**Comment by sangonzal** [comment]
@marcinzi #213 was merged. Thanks for contributing to the project!
