### ISSUE TITLE
JWT ID (jti) Claim Missing for Servers Requiring It

### ISSUE THREAD

**Issue by jviafora** [AzureAD/azure-activedirectory-library-for-java#215]
Suggest adding the following to JwtHelper Class:

Change this:
```java
final JWTClaimsSet claimsSet = new JWTClaimsSet.Builder()
                .audience(Collections.singletonList(jwtAudience))
                .issuer(credential.getClientId())
                .notBeforeTime(new Date(time))
                .expirationTime(new Date(time
                                + AuthenticationConstants.AAD_JWT_TOKEN_LIFETIME_SECONDS
                                * 1000))
                .subject(credential.getClientId())
                .build();
```

To this:
```java
final JWTClaimsSet claimsSet = new JWTClaimsSet.Builder()
                .audience(Collections.singletonList(jwtAudience))
                .issuer(credential.getClientId())
                .jwtID(UUID.randomUUID().toString())
                .notBeforeTime(new Date(time))
                .expirationTime(new Date(time
                                + AuthenticationConstants.AAD_JWT_TOKEN_LIFETIME_SECONDS
                                * 1000))
                .subject(credential.getClientId())
                .build();
```

**Comment by jviafora** [comment]
Would this be an accepted change if we created a PR for it? I noticed you initialize the JWTClaimsSet with jwtID in OAuthRequestValidationTest:
`// Prepare JWT with claims set
        JWTClaimsSet.Builder builder = new JWTClaimsSet.Builder();
        builder.issuer("alice");
        builder.subject("alice");
        List<String> aud = new ArrayList<String>();
        aud.add("https://app-one.com");
        aud.add("https://app-two.com");
        builder.audience(aud);
        // Set expiration in 10 minutes
        builder.expirationTime(new Date(new Date().getTime() + 1000*60*10));
        builder.notBeforeTime(new Date());
        builder.issueTime(new Date());
        builder.jwtID(UUID.randomUUID().toString());

        JWTClaimsSet jwtClaims = builder.build();`

**Comment by jviafora** [comment]
@sangonzal PR created:
[Pull Request](https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/217)

**Comment by olgapop** [comment]
Hi @sangonzal, do you know how long it takes for @SomkaPe to review changes? It's been 6 days already.

**Comment by psignoret** [comment]
@olgapop Quick question on this: In which situation are you finding that `jti` is required?

**Comment by jviafora** [comment]
@psignoret, on-prem ADFS
