### ISSUE TITLE
Change Maven artifactId to a more concise name

### ISSUE THREAD

**Issue by brunoborges** [AzureAD/azure-activedirectory-library-for-java#216]
Hi,

Almost all Azure related Java libraries have a concise artifactId representing they are in fact Azure-related. This project publishes a Maven artifact named "adal4j".

Is it possible to release the next version, and re-release version 1.5.0 (latest as of today), named "azure-activedirectory" ?

Thanks

**Comment by sangonzal** [comment]
Hi @brunoborges are there any other specific reasons why you think the named should be changed? Although I agree that having the whole name spelled out would be nice for consistency reasons, changing it at this point might introduce confusion to customers that have been using the library. Also, although not referenced in the artifact id, azure is list in the groupId (com.microsoft.azure)

**Comment by brunoborges** [comment]
Main reason is really to bring consistency across all Maven artifacts. But it also has impact in IDEs with code completion that look into Maven index. One developer may type "<artifactId>azure-" and the IDE will show all possible options. Or type "active" or "activedirectory" and it will find it. "adal4j" is not intuitive at all.

**Comment by sangonzal** [comment]
@brunoborges we have decided to keep the current name as to not introduce any confusion to current customers. 

I think you bring up a good point though, and as we release Microsoft Authentication Library for Java, we will take your feedback into account and make sure the name is consistent with the rest of the azure libraries.
