### ISSUE TITLE
Aquire Token with username/password (ROPC) doesn't return id_token

### ISSUE THREAD

**Issue by psignoret** [AzureAD/azure-activedirectory-library-for-java#22]
`acquireToken(final String resource, final String clientId, final String username, final String password, final AuthenticationCallback callback)` does not include `scope=openid` in the Authentication Request, so no `id_token` is returned.

**Comment by psignoret** [comment]
Where this all started: http://stackoverflow.com/questions/30004002/getting-username-and-group-info-from-azure-using-adal4j

**Comment by kpanwar** [comment]
Fixed.
