### ISSUE TITLE
MFA Auth documentation or sample?

### ISSUE THREAD

**Issue by borjaevo** [AzureAD/azure-activedirectory-library-for-java#222]
I read on readme that from 1.3.0 version support for handling Conditional Access claims challenge was added. But, im having difficult to find documentation about or any sample. Where i can find info about conditional access using adal4j for a java native app?

**Comment by sangonzal** [comment]
@borjaevo you can find information on conditional access [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-conditional-access-developer). Also take a look at the web app sample (src/samples/web-app-samples-for-adal4j) for how to handle a claims challenge exception 
in Java

**Comment by navyasric** [comment]
@borjaevo - Closing this for now as it is answered in above comment. Please reopen if necessary.
