### ISSUE TITLE
Import in AsymmetricKeyCredential causes JDK 9+ compilation issues

### ISSUE THREAD

**Issue by JonathanGiles** [AzureAD/azure-activedirectory-library-for-java#231]
In JDK 9+, the `import sun.security.util.Length` statement in `AsymmetricKeyCredential` causes compilation failure, as this class (and package) is no longer public API. Ideally it would be removed to enable this SDK to be used in JDK 9+, but understandably this requires extra work to, e.g. reflection, to remove hardcoded dependencies and instead do runtime checks.

**Comment by sangonzal** [comment]
@JonathanGiles Thanks for pointing this out. This is currently an open item on our backlog.

**Comment by brunoborges** [comment]
@sangonzal can you please reopen this issue and keep it open until it is actually delivered?

**Comment by sangonzal** [comment]
@brunoborges sure

**Comment by sangonzal** [comment]
@JonathanGiles @brunoborges use of sun.security.util.Length has been removed as of v1.6.4
