### ISSUE TITLE
Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: Server returned HTTP response code: 500 for URL : https://idpsso.XX.com/idp/sts.wst?TokenProcessorId=UsernameTokenProcessor

### ISSUE THREAD

**Issue by jainanuj82** [AzureAD/azure-activedirectory-library-for-java#232]
Hello,

i am trying to get Token using the PublicClient.java sample program.

But i am getting below error:

Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: Server returned HTTP response code: 500 for URL : https://idpsso.XX.com/idp/sts.wst?TokenProcessorId=UsernameTokenProcessor

The last URL is URL of my ping federate. 

The connectivity to office365 works well in my company. I am using federated account to fetch the token and then try to embed power BI report in a webapplication.

The code works well if i do not use a federated account.

Thanks for your support.

**Comment by jainanuj82** [comment]
Also, i can not see anything on fiddler.

**Comment by SomkaPe** [comment]
Based on server response I would assume that PingFederate Integration with Azure Active Directory is not configured.
