### ISSUE TITLE
AAD token with "invalid_grant" error when trying to pass as on-behalf of token to Graph API.

### ISSUE THREAD

**Issue by vedeevi** [AzureAD/azure-activedirectory-library-for-java#233]
Hi All,

We having an issue when trying to generate a AAD token using UserAssertion and client credentials for targeting to Graph API as resource. Following are our configurations which were used to send the request...

https://login.microsoftonline.com:443/{tenantId}/oauth2/v2.0/token
With this parameters :
client_id: app id declare inside Azure
client_secret : secret declare for the app inside azure
assertion : user token obtain AAD during sign-in to application
scope : https://graph.microsoft.com/user.read offline_access
requested_token_use : on_behalf_of
grant_type : urn:ietf:params:oauth:grant-type:jwt-bearer
client_assertion_type : urn:ietf:params:oauth:client-assertion-type:jwt-bearer

response :
{"error":"invalid_grant","error_description":"AADSTS50013: Assertion contains an invalid signature. [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: 'EFF66E7F5B6F9302F161A1D2DEAEA5523518206C', Found key 'Start=06/21/2018 00:00:00, End=06/21/2020 00:00:00']\r\nTrace ID: 6161cc29-60c1-4264-8469-342152201c00\r\nCorrelation ID: 95d6c4b6-a414-4510-b131-3775af8c1801\r\nTimestamp: 2018-08-28 09:33:19Z","error_codes":[50013],"timestamp":"2018-08-28 09:33:19Z","trace_id":"6161cc29-60c1-4264-8469-342152201c00","correlation_id":"95d6c4b6-a414-4510-b131-3775af8c1801"}

Please let us know what is the issue with this...

Thanks & Regards,
VDeevi

**Comment by sangonzal** [comment]
Hi @vedeevi are you using azure active directory library for Java? The Java library does not support the v2 endpoint. Here is a [link](https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison) explaining the differences between v1 and v2.

You might want to take a look at [MSAL.NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), which does support the v2 endpoint.

**Comment by ibigbug** [comment]
@vedeevi  did you fix the issue?
