### ISSUE TITLE
ADAL4J: v1.6.2 not released on GitHub?

### ISSUE THREAD

**Issue by cheenamalhotra** [AzureAD/azure-activedirectory-library-for-java#234]
I just came across new maven release version of adal4j 1.6.2 on Maven Repository (released 20 Aug), but don't see that released and tagged on GitHub. Is the source code tagging due sometime?

Would be good to know if v1.6.2 is a Pre-release of a Stable one.

**Comment by sangonzal** [comment]
Hi @cheenamalhotra thanks for pointing this out, releases on GitHub should now be up to date. v1.6.2 is a stable release.
