### ISSUE TITLE
Seamless SSO fails with integrated authentication

### ISSUE THREAD

**Issue by fiechter** [AzureAD/azure-activedirectory-library-for-java#235]
The following request should use negotiate authentication according to the docs:
context.acquireToken(resource, clientId,userName, null, callback);

Somehow, users enabled for seamless SSO give this exception:
com.microsoft.aad.adal4j.AuthenticationException: Password is required for managed user

**Comment by fiechter** [comment]
Any chances that this support will come?

**Comment by sangonzal** [comment]
@fiechter ADAL4J 1.6.3 and higher now has support for non-interactive sign-in with Integrated Windows Authentication when Seamless SSO is enabled.
