### ISSUE TITLE
Not able to Build ADAL4J library with Java 11

### ISSUE THREAD

**Issue by cheenamalhotra** [AzureAD/azure-activedirectory-library-for-java#238]
As per steps defined in [WIKI](https://github.com/AzureAD/azure-activedirectory-library-for-java/wiki/Maven), performing `mvn clean package` attempts running Test Suite and fails with below error:

![image](https://user-images.githubusercontent.com/13396919/46499311-931dd480-c7d4-11e8-9ddb-9292e924bcf9.png)

Log attached: [adal4j.txt](https://github.com/AzureAD/azure-activedirectory-library-for-java/files/2447960/adal4j.txt)

Looks like ADAL4J cannot build with JDK 11, any plans to support Java 11 in future?

**Comment by sangonzal** [comment]
@cheenamalhotra ADAL4J does not currently have any plans to support Java 11 as of right now. This might be revisited in the future.

We are currently working on MSAL Java, which will have support for later versions of Java.
