### ISSUE TITLE
Does the SDK support acquiring MSI authentication token?

### ISSUE THREAD

**Issue by yvgopal** [AzureAD/azure-activedirectory-library-for-java#243]
I am from Azure service bus team. Our SDK supports AAD authentication, and of course MSI too. AAD library for .net has API to get a MSI authentication token (from documentation)
`var azureServiceTokenProvider = new AzureServiceTokenProvider();
string accessToken = await azureServiceTokenProvider.GetAccessTokenAsync("https://management.azure.com/");`

Do you have something similar in ADAL4J library? We are currently fetching the token from a hard coded http URL on the VM ( which apparently is no longer the recommended way).

If you don't have it now, are you planning to add it to the java SDK? If yes, when can we expect it?

Thanks,
Vijay

**Comment by sangonzal** [comment]
Issue was resolved offline. 

For anyone looking to use MSI authentication, Azure Java SDK supports MSI: : https://azure.github.io/azure-sdk-for-java/com/microsoft/azure/credentials/MSICredentials.html

Sample showing how to use it: https://github.com/Azure-Samples/compute-java-manage-vm-from-vm-with-msi-credentials/blob/master/src/main/java/com/microsoft/azure/management/compute/samples/ManageVirtualMachineFromMSIEnabledVirtualMachine.java#L51-L64.
