### ISSUE TITLE
Consider options to simplify configuring of SSLTunnelSocketFactory for corporate proxies.  

### ISSUE THREAD

**Issue by SomkaPe** [AzureAD/azure-activedirectory-library-for-java#245]
Consider options to simplify configuring of SSLTunnelSocketFactory for corporate proxies.

**Comment by danield137** [comment]
@SomkaPe how about we try to get it from system environment variables and set the proxy in `AuthenticationContext` ctor?

**Comment by sangonzal** [comment]
ADAL4J is in maintenance mode and no new features will be added going forward except for security fixes. A workaround has been provided in MSAL4J, by allowing users to configure Http client.
