### ISSUE TITLE
It's not possible to get the full name  of a user

### ISSUE THREAD

**Issue by julienlancelot** [AzureAD/azure-activedirectory-library-for-java#249]
Hi,

I'm trying to access to the "name" of the user, but I couldn't.
As this field is the only mandatory field in Azure Active Directory, it's the only one I could safely rely on, because currently it's possible to have user without any name as first and last name can be empty.

From what I see in the code, first name (https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/main/java/com/microsoft/aad/adal4j/UserInfo.java#L70) and last name (https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/main/java/com/microsoft/aad/adal4j/UserInfo.java#L79) are easily available.

When debugging the authentication, I see that the name is available in the claims (https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/main/java/com/microsoft/aad/adal4j/UserInfo.java#L113), but unfortunately there's no getter for it.

Thanks in advance for your help !

**Comment by julienlancelot** [comment]
After digging further on this issue, I've found that I were able to get the name by doing : 
```
(String) JWTParser.parse(authenticationResult.getIdToken()).getJWTClaimsSet().getClaim("name")
```

My only concern is  : is the "name" always provided in the JWT claims ?

**Comment by sangonzal** [comment]
@julienlancelot Were able to solve this offline with @jmprieur help?

**Comment by julienlancelot** [comment]
Indeed, I forgot to do an update here, thanks to @jmprieur I've been able to get the name of the user by using the entry point /me from [Graph API](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0).
This issue is then solved
