### ISSUE TITLE
Token cache

### ISSUE THREAD

**Issue by toshetah** [AzureAD/azure-activedirectory-library-for-java#253]
Hi!

I was wondering if there is a concept of token cache in the java implementation of this library.
In other libraries published by adal (e.g. .Net, python, and node) there is a default token cache, and implementation of refreshing tokens using the refresh tokens.
I couldn't find it in this repo.
Did I miss something? Is that on purpose? Are you planing on adding it?

Thanks!
@ohbitton as FYI.

**Comment by sangonzal** [comment]
@toshetah You are right, ADAL4J does not have a token cache, and there are no current plans to add it. We are currently working on MSAL Java, which will have all features included in ADAL, as well as other features including the token cache, telemetry, and many other [things that come with MSALs](https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison)

**Comment by toshetah** [comment]
Thanks Santiago! I'll be waiting for the v2 version.

**Comment by sangonzal** [comment]
Hi @toshetah, just wanted to provide an update on the v2 version - we have release MSAL and it now how support for caching tokens. You can find it in the [MSAL github repo](https://github.com/AzureAD/microsoft-authentication-library-for-java). Happy to help with any questions/ problems you run into as you work to migrate your code over.
