### ISSUE TITLE
Using mobile access token for authentication

### ISSUE THREAD

**Issue by chan4lk** [AzureAD/azure-activedirectory-library-for-java#256]
I have a mobile app which gets token directly from azure login. And I have a service which is using adal4j in spring boot. I cannot use the mobile generated token to authenticate spring service. Becase I use two different azure app registrations for mobile and web service. Is there a way to accomplish this ?

**Comment by sangonzal** [comment]
@chan4lk Have you tried using on On-Behalf-Of flow? Here is some documentation that you might find useful: [ADAL4J Wiki](https://github.com/AzureAD/azure-activedirectory-library-for-java/wiki/Service-to-service-calls-on-behalf-of-the-user) and [Microsoft Docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-on-behalf-of-flow)

**Comment by chan4lk** [comment]
I added web registration as a required api inside mobile app registration. And the token generated from mobile is now accepted in adal4j. Thank you.
