### ISSUE TITLE
UserInfo should expose groups when included

### ISSUE THREAD

**Issue by psignoret** [AzureAD/azure-activedirectory-library-for-java#26]
When `id_token` includes `groups` claim, they should be retrievable via UserInfo.

**Comment by psignoret** [comment]
After looking at other ADAL implementations, UserInfo might not be the right place to expose the groups, but still needs to be a method to access the `id_token` claims from the Authentication Response.

**Comment by kpanwar** [comment]
raw id_token can be used to parse out the claims.

**Comment by solokingjec** [comment]
@kpanwar do you have an implementation on how to get the user group of the current user?
