### ISSUE TITLE
Authority validation boolean has no effect

### ISSUE THREAD

**Issue by mwm-twx** [AzureAD/azure-activedirectory-library-for-java#260]
ADAL4J version 1.6.3

`AuthenticationContext` accepts a `validateAuthority` boolean, which is passed to `AuthenticationAuthority`.  While the boolean is used in `AuthenticationAuthority`, it doesn't actually prevent validation, as that occurs directly after the assignment:

```java
    AuthenticationAuthority(final URL authorityUrl, final boolean validateAuthority) {
        this.authorityUrl = authorityUrl;
        this.authorityType = detectAuthorityType();
        this.validateAuthority = validateAuthority;
        validateAuthorityUrl();
        setupAuthorityProperties();
    }
```

`validateAuthorityUrl()` does not exit if `validateAuthority` is `false`.

**Comment by sangonzal** [comment]
@mwm-twx There are two types of validation that happen here: 

1. That authority URL is correctly formatted 
2. That the authority is trusted by Azure AD.

The URL validation will always happen regardless of whether validateAuthority is set to true or false. The validateAuthority boolean is used for the second type of validation, which checks that the authority that was passed in is in the list of authorities that are trusted by Azure AD.

**Comment by mwm-twx** [comment]
Okay.  So there is no way to use a non-https scheme with ADAL then?

**Comment by sangonzal** [comment]
@mwm-twx that's right

**Comment by mwm-twx** [comment]
Thanks.
