### ISSUE TITLE
authenticate against on-premise OIDC server

### ISSUE THREAD

**Issue by mtuppad** [AzureAD/azure-activedirectory-library-for-java#262]
Can this library be used to authenticate against on-prem OIDC server. 

Currently when we use this library this is the flow that followed. 
1. User hits www.myapp.com
2. Since user is not authenticated, will redirected to Microsoft login page <<we need to avoid this>>
3. User enters email id and user is redirected to on prem OIDC end point - (Azure AD is configured this way) oidc-prod.mycorp.com 
4. user enters username and password, gets authenticated, and redirected back to myapp. 

We would like to skip step 2 and directly redirect to on-pre OIDC server? (apps can access this end point)

App is hosted in azure AKS.

**Comment by sangonzal** [comment]
@mtuppad what on-premise OIDC server and which authentication flow are you using?

**Comment by mtuppad** [comment]
> @mtuppad what on-premise OIDC server and which authentication flow are you using?

The on prem IDP is Ping Federate and we are using Oauth2 and OpenID connect. 
Apps are based on Typescripts technology (Dojo or Angular) and backend are spring boot based rest APIs

**Comment by sangonzal** [comment]
@mtuppad I believe this will not work. This is not a scenario we support or which we have tested.
