### ISSUE TITLE
Missing POM for adal4j v1.6.4

### ISSUE THREAD

**Issue by lpfeup** [AzureAD/azure-activedirectory-library-for-java#265]
Got the following error on `mvn compile` when updating to 1.6.4:

```
Downloading: https://repo.maven.apache.org/maven2/com/microsoft/azure/adal4j/1.6.4/adal4j-1.6.4.pom
[WARNING] The POM for com.microsoft.azure:adal4j:jar:1.6.4 is missing, no dependency information available
```

Checked https://mvnrepository.com/artifact/com.microsoft.azure/adal4j/1.6.4 and no Compile Dependencies are shown either.

Thanks in advance

**Comment by sangonzal** [comment]
@lpfeup I have uploaded again and it is working locally for me. Can you try again and confirm whether or not it is working for you?

https://mvnrepository.com/artifact/com.microsoft.azure/adal4j/1.6.4  will probably take a couple of hours to update, but compile dependencies should be listed on there.

**Comment by lpfeup** [comment]
@sangonzal I can confirm it is working now.

Thanks!
