### ISSUE TITLE
Unable to reset password of a user : Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by varun-kulkarni24** [AzureAD/azure-activedirectory-library-for-java#266]
Hello,
I wan't to use Azure AD graph API(without any sign-in user info) in my java application, But I am getting error message "Insufficient privileges to complete the operation." 

**Following is the code snippet :** 

```MediaType mediaType = MediaType.parse("application/json; charset=utf-8");
            OkHttpClient client = new OkHttpClient();
            JsonObject patchBody = new JsonObject();
            JsonObject passwordBody = new JsonObject();
            passwordBody.put("password", "Testing@1234");
            passwordBody.put("forceChangePasswordNextLogin", Boolean.TRUE);
            patchBody.put("passwordProfile", passwordBody);
            RequestBody requestBody = RequestBody.create(mediaType, patchBody.toString());
            Request request = new Request.Builder().url(String.format("https://graph.windows.net/testing.onmicrosoft.com/users/********-1ade-4315-8003-0d1f9bac****?api-version=1.6"))
                    .addHeader("cache-control", "no-cache")
                    .patch(requestBody)
                    .addHeader("Authorization", "Bearer " + result.getAccessToken()).build();
            Response response = client.newCall(request).execute();
                String jsonData = response.body().string();
```

**This returns response as :** 

```{"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"b5f7f10f-b97e-40ac-9f44-6e5f40a005b3","date":"2019-04-24T07:20:52"}}```

Also I have tried with list users, update user API's and the similar code worked for the same. It is restricting me for reset password and delete user API's.
I referred the document and also given application permissions to the App.
![App permissions](https://user-images.githubusercontent.com/22593135/56647905-e3d91a00-669f-11e9-8067-15757212f93e.png)

Please help me out in this.

**Comment by sangonzal** [comment]
@varun-kulkarni24 I don't see permissions listed for resetting passwords or deleting users in the screenshot you attached. I would make sure those permissions are granted to your application.

**Comment by thikon** [comment]
@varun-kulkarni24 i tried to allow all of the application and delegated permission and the result is "Insufficient privileges to complete the operation." (same your result)

Did you add some config about reset password policy on acquire token step?

**Comment by sangonzal** [comment]
@varun-kulkarni24 @thikon It seems that the reset password and delete user API's require you to be an administrator in the tenant. Refer to this [issue](https://github.com/Azure/azure-sdk-for-node/issues/2280) for more information.
