### ISSUE TITLE
daemon certificate credential

### ISSUE THREAD

**Issue by wassimmansour** [AzureAD/azure-activedirectory-library-for-java#275]
The dotnetcore library has the ClientAssertionCertificate class that allows getting a token using a clientId and a certificate. I need to do the exact same thing except in Java. Is there a way to achieve that using this library?

Thanks.

**Comment by sangonzal** [comment]
@wassimmansour Yes what you are looking for is [AsymmetricKeyCredential](https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/main/java/com/microsoft/aad/adal4j/AsymmetricKeyCredential.java). 

As a side note: We have released a preview of [MSAL Java](https://github.com/AzureAD/microsoft-authentication-library-for-java), which has support for the Microsoft V2 endpoint, as well as adds a lot of  [features](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/master/changelog.txt) on top of ADAL. For MSAL, you'll want to use the [ClientCredentialFactory](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/ClientCredentialFactory.java)

**Comment by wassimmansour** [comment]
@sangonzal Thank you very much for the quick response.
