### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [AzureAD/azure-activedirectory-library-for-java#276]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/microsoft/aad/adal4j/AsymmetricKeyCredential.java: Line number => 163: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => src/main/java/com/microsoft/aad/adal4j/AsymmetricKeyCredential.java: Line number => 194: API name => MessageDigest:<BR> File name => src/main/java/com/microsoft/aad/adal4j/AsymmetricKeyCredential.java: Line number => 167: API name => KeyStore:<BR> File name => src/main/java/com/microsoft/aad/adal4j/AsymmetricKeyCredential.java: Line number => 192: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by sangonzal** [comment]
@mhp0rtal The lines you have pointed out are not aligned to the APIs you are listing - for example line [163] points to this (https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/main/java/com/microsoft/aad/adal4j/AsymmetricKeyCredential.java#L163). Can you please clarify? 

I'm assuming you are taking about this [line](https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/main/java/com/microsoft/aad/adal4j/AsymmetricKeyCredential.java#L169). [Java documentation](https://docs.oracle.com/javase/7/docs/api/java/security/KeyStore.html#getInstance(java.lang.String,%20java.lang.String)) for this API states that java.lang.String is a valid parameters.  Could you expand on why you believe this is a API misuse?

And this [line](https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/main/java/com/microsoft/aad/adal4j/AsymmetricKeyCredential.java#L197). You are right that the passed in value could be either SHA-256, SHA-384, SHA-512. It is returning a SHA-1 hash right now, but if you need to calculate the hash with another one of the algorithms you listed you can call [getPublicCertificate](https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/main/java/com/microsoft/aad/adal4j/AsymmetricKeyCredential.java#L134) and calculate the hash yourself.

**Comment by sangonzal** [comment]
Seems to be a bot spamming hundreds of libraries: https://github.com/mob41/broadlink-java-api/issues/22
