### ISSUE TITLE
"The server was unable to process the request due to an internal error" when using app-only auth with only client ID and client secret

### ISSUE THREAD

**Issue by nddipiazza** [AzureAD/azure-activedirectory-library-for-java#277]
We created a Sharepoint Online application so we can do app-only auth.

We followed these steps to create an app.

https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs

We want to avoid using a refresh token if possible when doing app-auth with SharePoint online from a third-party Java application, and we don't to use the private-key either.

Code snippet we use to generate an auth code:

```
String tenant = "mytenant.onmicrosoft.com";
String azureLoginEndpoint = "https://login.windows.net";
String authority = String.format("%s/%s/", StringUtils.trim(azureLoginEndpoint), StringUtils.trim(tenant));
AuthenticationContext authenticationContext = new AuthenticationContext(authority, true, executorService);
tokenResult = authenticationContext.acquireToken(sharepointWebApplicationUrl,
         new ClientCredential(org.apache.commons.lang3.StringUtils.trim(clientId), org.apache.commons.lang3.StringUtils.trim(clientSecret)), callback);
```

When I try to use the bearer token returned, I get:

```
Error message: [{"error_description":"The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs."}]
```

But when I use the SharePoint CorePnP C# nuget package

```
using OfficeDevPnP.Core;
using System;

class Program {
  static void Main(string[] args) {
    string siteUrl = "https://mytenant.sharepoint.com";
    using (var cc = new AuthenticationManager().GetAppOnlyAuthenticatedContext(siteUrl, "bdad....36cd", "x....=")) {
      cc.Load(cc.Web, p => p.Title);
      cc.ExecuteQuery();
      Console.WriteLine(cc.Web.Title);
    };
  }
}
```

This works. I'm able to get authenticated fine. 

Am I missing something?

**Comment by sangonzal** [comment]
@nddipiazza If I'm understanding correctly, you are able to acquire a token successfully but then running into issues using this token with SharePoint online?  Have you tried to follow any of the debugging steps provided in the error message?

**Comment by nddipiazza** [comment]
That's correct. I was able to reverse engineer the oauth process by using `OfficeDevPnP.Core` source code. We should compare and make sure that it is expected a token from ADAL4J's acquireToken is expected not to work in sharepoint online when using only clientID, clientSecret.

**Comment by sangonzal** [comment]
@nddipiazza I see. In this case, I'm not sure this is the right channel for this issue. From ADAL4Js perspective, if you are able to acquire a token from Azure AD for a given resource successfully, then ADAL's job is complete.  I'm not sure how Sharepoint is validating or using tokens on their end that is causing the internal error (I also don't have access to that server). I would reach out to the Sharepoint Online team and see if they are able to help out.
