### ISSUE TITLE
Authentication fails if password contains ampersand

### ISSUE THREAD

**Issue by mtommila** [AzureAD/azure-activedirectory-library-for-java#28]
AuthenticationContext.acquireToken(String resource, String clientId, String username, String password, AuthenticationCallback callback) fails always with a 400 server response if the password contains some characters that would need to be XML escaped, e.g. '&'.

Apparently the password (and maybe the username?) are put to the SOAP body un-escaped and thus when the password contains '&' the XML is not well-formed, and the server responds with a 400.

The fix should be, obviously, to correctly XML escape text so that the SOAP body is well-formed XML.

**Comment by kpanwar** [comment]
Fixed.
