### ISSUE TITLE
 object aad is not a member of package com.microsoft

### ISSUE THREAD

**Issue by sara85sara** [AzureAD/azure-activedirectory-library-for-java#291]
I am getting following message in databricks, even though I have installed adal4j package.

import com.microsoft.aad.adal4j.ClientCredential
import com.microsoft.aad.adal4j.AuthenticationContext
import java.util.concurrent.Executors
 
val TenantId = "******************";
val authority = "https://login.windows.net/" + TenantId;
val resourceAppIdURI = "https://database.windows.net/";
val ServicePrincipalId = "******";
val ServicePrincipalPwd = "*****";

val service = Executors.newFixedThreadPool(1);
val context = new AuthenticationContext(authority, true, service);

//Get access token
val ClientCred = new ClientCredential(ServicePrincipalId, ServicePrincipalPwd);
val authResult = context.acquireToken(resourceAppIdURI, ClientCred, null);
val accessToken = authResult.get().getAccessToken

command-2686928155452854:3: error: object aad is not a member of package com.microsoft
import com.microsoft.aad.adal4j.AuthenticationContext
                     ^
command-2686928155452854:13: error: not found: type AuthenticationContext
val context = new AuthenticationContext(authority, true, service);
                  ^
command-2686928155452854:2: error: object aad is not a member of package com.microsoft
import com.microsoft.aad.adal4j.ClientCredential
                     ^
command-2686928155452854:16: error: not found: type ClientCredential
val ClientCred = new ClientCredential(ServicePrincipalId, ServicePrincipalPwd);

**Comment by sangonzal** [comment]
@sara85sara How did you add adal4j into your project?

**Comment by sara85sara** [comment]
I installed from maven library package from databricks... Now I have un-installed the package and downloaded the jar from maven and loaded back to databricks DFS.  now getting the token. but its not consistent.. I have restart the cluster everytime...

**Comment by sangonzal** [comment]
@sara85sara this is a question for the databricks team, nothing we can do on our end.
