### ISSUE TITLE
x509CertThumbprint is deprecated

### ISSUE THREAD

**Issue by toshetah** [AzureAD/azure-activedirectory-library-for-java#292]
x509CertThumbprint at the nimbus library is deprecated.
It is used at [JwtHelper](https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/d2afdbbc5db9d4b056225379c0ec51412942331d/src/main/java/com/microsoft/aad/adal4j/JwtHelper.java#L77) helping acquiring the JWT.
In addition, according to [Microsoft identity platform access tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#header-claims) x5t  is a legacy claim emitted only in v1.0 access tokens for compatibility purposes.

Can you please fix that?
Thanks!

**Comment by henrik-me** [comment]
@toshetah, we highly recommend that you are moving to msa4j, the updated auth library. We are not planning any updates to adal4j. If you see any issues using msal4j please let us know.
Our Migration guide is available here: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-adal-msal-java

**Comment by henrik-me** [comment]
I'm closing this issue, however feel free to re-active with additional information.
