### ISSUE TITLE
can use it for SCIM

### ISSUE THREAD

**Issue by liangkunJoin** [AzureAD/azure-activedirectory-library-for-java#302]
In my application, it needs to be associated with Microsoft's pre configured functions. The official code is the C # version, but I only know Java. Can I encapsulate Microsoft's underlying verification related requests through your lib package.can your give me a java demo for SCIM. Thanks!

**Comment by sangonzal** [comment]
@liangkunJoin ADAL only supports OAuth2.0 and OpenID Connect. SCIM seems to be a different protocol, which is not supported by either ADAL or [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-java)
