### ISSUE TITLE
Latest adal4j 1.6.6 uses oauth2-oidc-sdk 7.4 which is vulnerable to XXE Injection

### ISSUE THREAD

**Issue by PayalDodeja** [AzureAD/azure-activedirectory-library-for-java#305]
ADALJ latest 1.6.6 uses version 7.4 of oauth2-oidc-sdk which is supposedly vulnerable to XEE Injection. 
Refer: [https://snyk.io/vuln/SNYK-JAVA-COMNIMBUSDS-1243767](url)

The issue was reported as part of sonatype-2021-0429, with CWE:[611](https://cwe.mitre.org/data/definitions/611.html)

If we move to the version with the fix for oauth2-oidc-sdk, that is version 8.36.2, version 9.3.1 and above , it complaints about ClassNotFound Error for CommonContentTypes which is being used by ADALJ. And we are using adal4j in order to acquire token for authenticating credentials.

**Actual:** ADAL using vulnerable version of oauth2-oidc-sdk
**Expectation:** ADAL to use the non-vulnerable version of auth2-oidc-sdk

**Note: CommonContentTypes class was removed from oauth2-oidc-sdk from version 8.0 and above. Apparently ADAL is using that while acquiring token for authentication.**

**Comment by sangonzal** [comment]
Thanks for reporting this @PayalDodeja we will work to update oauth2-oidc-sdk and will release a new version of ADAL with update dependencies by the end of the week.

**Comment by Avery-Dunn** [comment]
Hello @PayalDodeja : A new version of ADAL, [1.6.7](https://github.com/AzureAD/azure-activedirectory-library-for-java/releases/tag/1.6.7), has just been released with version 9.4 of oauth2-oidc-sdk to address these issues (though it may take up to a few hours for Maven to show this version),

**Comment by PayalDodeja** [comment]
thanks for the update @Avery-Dunn
