### ISSUE TITLE
What is the good uniqueId

### ISSUE THREAD

**Issue by myosotys** [AzureAD/azure-activedirectory-library-for-java#35]
Hello, 
I have a problem with my app which use Azure for Authentication. I need to get the objectId of the user, but when i get the UserInfo, the uniqueId is the "Token_subject". 
I found in code the problem in UserInfo.java:
```java
if (!StringHelper.isBlank(claims
                .getStringClaim(AuthenticationConstants.ID_TOKEN_OBJECT_ID))) {
            
            uniqueId = claims.getStringClaim(AuthenticationConstants.ID_TOKEN_OBJECT_ID);
            
        } else if (!StringHelper.isBlank(claims
                .getStringClaim(AuthenticationConstants.ID_TOKEN_SUBJECT))) {
            
            uniqueId = claims.getStringClaim(AuthenticationConstants.ID_TOKEN_SUBJECT);
            
        }
```
In object claims, "object_id" is null, and the good object ID is in claims.getCustomClaim (with key "oid")

I don't know if the problem come from a bad utilisation of the app or Azure or if it is a real problem. I fork to try to get "oid" in customClaim before "object_id" but i want to know if i am right or not.

**Comment by omercs** [comment]
@myosotys : This looks like a bug.
Field constant should be "oid". Adal.net uses oid: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/src/ADAL.Common/OAuthConstants.cs

**Comment by kpanwar** [comment]
Fixed. Pending release.
