### ISSUE TITLE
AADSTS50034

### ISSUE THREAD

**Issue by sethulakshmipraveen** [AzureAD/azure-activedirectory-library-for-java#38]
I am gettign this exception when trying to get the token from the application created in active directory.
java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error":"invalid_grant","error_description":"AADSTS50034: To sign into this application the account must be added to the***** directory.\r\nTrace ID: 83910367-b165-4e60-b0a8-057dd760c910\r\nCorrelation ID: 2d045d7b-1ed9-48b1-8624-45e7334976a0\r\nTimestamp: 2015-07-02 11:41:29Z"}

But with the same credentials the C# code is giving me the token. Only difference i see is in parameters to get the token, the C# method accepts the url too as a parameter and not the user name and password, where as java code accepts user name and password not url. Please help

**Comment by RandalliLama** [comment]
@sethulakshmipraveen Are you using 'common' authority, or a specific tenant?

**Comment by metal-hed** [comment]
@RandalliLama I know this is an old issue, but I am having similar issues using the library. I am using a specific tenant authority to access the token URL. The same user with the same credentials is able to login to Sharepoint via their browser so I am able to rule that out as a suspect. The same code has worked for other users in the tenant domain but a few are seeing the issue above.

Is there anything else I should check to verify everything is setup correctly?

**Comment by RandalliLama** [comment]
Could you provide an updated error message with Correlation ID and timestamp.  @kpanwar Do we have good logging in the Java ADAL?  Would it be worth collecting those?

**Comment by metal-hed** [comment]
@RandalliLama In my case the issue is solved. It turns out the user was using just their login id to try and authenticate. Once the user used their full email address everything worked as expected.

ex. user@company.com worked fine but the user was trying to login with 'user'

**Comment by RandalliLama** [comment]
@metal-hed Great.  Glad you're unblocked.  Thanks for the update.

**Comment by tarry87** [comment]
Hi Team,

im getting the below error :

Login-AzAccount : AADSTS50034: The user account {EmailHidden} does not exist in the xxxx directory. To sign into this application, the account must 
be added to the directory.
Trace ID: 7b9c49f2-61a9-42e8-990c-afaef7da6b00
Correlation ID: 1f6e26cf-1a28-4626-8382-4798faa86b0c
Timestamp: 2019-10-18 09:26:31Z
At line:1 char:1
+ Login-AzAccount -Credential $cred -TenantId "xxxxx- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], AdalServiceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand 

Please help.

**Comment by vitaliidasaev** [comment]
for tenant authentication try to use User Principal Name instead of email

**Comment by cbbrsc** [comment]
I'm using User Principal Name and I have the same error
