### ISSUE TITLE
Adal4j 1.0.0:  common-codec dependency in SNAPSHOT

### ISSUE THREAD

**Issue by rguignard** [AzureAD/azure-activedirectory-library-for-java#40]
Hey

It seems that the adal4j library (http://mvnrepository.com/artifact/com.microsoft.azure/adal4j/1.0.0) imports a "common-codec" dependency in SNAPSHOT version. Is it normal ?

Best regards

Romain

**Comment by kpanwar** [comment]
fixed in 1.1.0
