### ISSUE TITLE
acquireToken overload with PromptBehavior and not UserIdentity raises nullpointerexception

### ISSUE THREAD

**Issue by JohnAustin-MSFT** [AzureAD/azure-activedirectory-library-for-java#47]
When you make the call to this overload:
public void acquireToken(Activity activity, String[] scope, String[] additionalScope, String clientId, String redirectUri, PromptBehavior prompt, AuthenticationCallback<AuthenticationResult> callback)

The AuthorizationRequest object is passed a null UserIdentity and throws a NullPointerException.

My assumption is that if the acquireToken overload does not take a UserIdentity, then a null UserIdentity should be accounted for and allowed.

**Comment by kpanwar** [comment]
This issue belongs to https://github.com/AzureAD/azure-activedirectory-library-for-android
