### ISSUE TITLE
Create real documentation (generate the javadocs) for ADAL-java

### ISSUE THREAD

**Issue by jmspring** [AzureAD/azure-activedirectory-library-for-java#51]
On the main project page -- "We provide a full suite of sample applications and documentation on GitHub to help you get started with learning the Azure Identity system. "

There are no javadocs in the the link in the above text.  Further, the examples included are basically the same as those in the azure-activedirectory-library-for-java repository.

**Comment by kpanwar** [comment]
@brandwe: can you take a look?

**Comment by brentschmaltz** [comment]
@SomkaPe what do we need to do here?

**Comment by dabe5** [comment]
Sadpur

**Comment by dabe5** [comment]
Ramakrishna
