### ISSUE TITLE
Option to specify an 'SSLSocketFactory' in Azure clients

### ISSUE THREAD

**Issue by jobinar** [AzureAD/azure-activedirectory-library-for-java#54]
Currently there is no way to configure Azure clients with a custom `SSLSocketFactory`. This is required for systems which communicate with different other servers (in addition to Azure) over HTTPS. There is a need to use different SSL Contexts (with different security configurations) to create SSL Socket factories to talk to these, since the validation logic is different for certain types of servers. Hence, we cannot set the default SSL context of the system to the one required by Azure as it will be a system wide change affecting the connections to other servers.

The rationale behind this change is to be able to create isolated SSL configurations for connecting to different servers, of which one is Azure.

**Comment by kpanwar** [comment]
Fixed in last release
