### ISSUE TITLE
Add support Proxy in HttpHelper

### ISSUE THREAD

**Issue by Vartlok** [AzureAD/azure-activedirectory-library-for-java#55]
Currently there is no way to configure AuthenticationContext to use Proxy for perform HTTP request.

**Comment by kpanwar** [comment]
@Vartlok - Did you get to try the approach provided in your question at http://stackoverflow.com/questions/32522773/adal-for-java-proxy ?

**Comment by satheeshaGowda** [comment]
Hi Kanishk,
            Think about the scenario where  you want to  set  proxy  only to specific http/https connections , not globally  at Application  level to all http/https connections.

Thanks!
Satheesha Gowda

**Comment by kpanwar** [comment]
@Vartlok - I left some code comments. Take a look when you get a chance.

**Comment by satheeshaGowda** [comment]
adal4j  1.1.0 (with proxy support) seems to be not working , Appears to be new library code change made to only to dynamic Instance discovery, not to calling part of token uri,  following is the way that am setting the proxy to the authentication context, please let me know if there are other means to do it, which I couldn’t find.
 
  ExecutorService service = Executors.newSingleThreadExecutor();
            PrivateKey privateKey = //getPrivatekey
            X509Certificate x509Cert = /getCert
            AsymmetricKeyCredential asymmetricKeyCredential = AsymmetricKeyCredential.create( clientId, privateKey, x509Cert );
            AuthenticationContext ctx = new AuthenticationContext( tokenEndpoint, true, service );
            ctx.setProxy( MdmProxyUtils.getProxy( tokenEndpoint ) );
            Future<AuthenticationResult> result = ctx.acquireToken( resourceId, asymmetricKeyCredential, null );
            AuthenticationResult ar = result.get();
            LOG.info( "[Succesful]Access Token - {}", ar.getAccessToken() );

**Comment by Vartlok** [comment]
Yes, It looks like I missed one place where HttoHelper is used. I'm not sure if I should reopen this issue or open a new one.

**Comment by kpanwar** [comment]
Fix is pending in https://github.com/AzureAD/azure-activedirectory-library-for-java/tree/sslfactory. I will release today.
