### ISSUE TITLE
Refresh Token fetched by this Java Library doesn't work

### ISSUE THREAD

**Issue by sourabhde** [AzureAD/azure-activedirectory-library-for-java#56]
The Refresh Token doesn't work when we try to authenticate with the desired service

**Comment by RandalliLama** [comment]
@sourabhde Could you provide more detail?  Exactly how are you using the refresh token?  Are you sending it to the resource service?  Are you asking ADAL to acquire a new access token via the refresh token?

**Comment by kpanwar** [comment]
@RandalliLama Issue turned out to be in @sourabhde's code where their resource was rejecting the token because of a trailing `/` in the resource claim inside the access token.
