### ISSUE TITLE
1.0.1 release

### ISSUE THREAD

**Issue by MikeN123** [AzureAD/azure-activedirectory-library-for-java#57]
1.0.1 seems to be 'released', but is nowhere to be found. May I suggest:

* Putting 1.0.1 on Maven Central or Bintray
* Tagging the 1.0.0 and 1.0.1 release versions in git
* Closing any issues that have been fixed
* Reworking the version numbering to a -RELEASE and -SNAPSHOT scheme, so everyone can see if something is a snapshot or a release
* Using the maven-deploy plugin to make life easier for everyone

**Comment by kpanwar** [comment]
It is not released into maven yet. We are working to get that resolved.

**Comment by Korporal** [comment]
I'm frustrated too, I can't locate any 1.0.1 version and trying to use a 1.0.0 version causes breakages. As it stands the repo cannot be used because we cannot build.

**Comment by kpanwar** [comment]
Repo builds correctly from the source. What error are you getting when running "mvn clean package" ?

**Comment by Korporal** [comment]
The pom file (sample-for-adal4j) refers to version 1.0.1 of artifact adal4j in group com.microsotf.azure.
I'm no guru on Java/Maven but the dependency is being flagged by Maven as an error.

**Comment by kpanwar** [comment]
ok, so specifically the sample is not building. We are still resolving some issues with the release. I will keep you posted on the progress. Till then you can install the local source build in your repository and use it.

**Comment by kpanwar** [comment]
just released 1.1.0
