### ISSUE TITLE
Executing PublicClient gives "The request body must contain the parameter- 'client_secret'

### ISSUE THREAD

**Issue by vikram-gore-sp** [AzureAD/azure-activedirectory-library-for-java#59]
While executing the PublicClient.java file it gives -
java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error":"invalid_request","error_description":"AADSTS90014: The request body must contain the following parameter: 'client_secret.

We have correct username,password, client id ,resource.
How to solve.

**Comment by kpanwar** [comment]
you are attempting to use web application credentials which require client secret. you should create a native application in your portal and use its client id.

**Comment by narottam-singh-sp** [comment]
Hi Kanishk, thanks for the response. So do you mean that web application credentials can't be used to authenticate the Azure AD users using their username and password?
