### ISSUE TITLE
Problem with on-behalf-of scenario

### ISSUE THREAD

**Issue by wadamczewski** [AzureAD/azure-activedirectory-library-for-java#67]
I am trying to use a JWT token that I have already obtained from an authenticated user (and passed to back-end from front-end) to use in the on-behalf-of scenario as follows:

```
private static AuthenticationResult getAccessTokenOnBehalfOfUser(String resourceId, String tenant, String clientId, String clientSecret, String userJwtToken) throws MalformedURLException, ServiceUnavailableException, ExecutionException, InterruptedException {

        ClientCredential clientCredential = new ClientCredential(clientId, clientSecret);
        ClientAssertion clientAssertion = new ClientAssertion(userJwtToken);

        AuthenticationContext context = null;
        AuthenticationResult result = null;
        ExecutorService service = null;
        try {
            service = Executors.newFixedThreadPool(1);
            context = new AuthenticationContext("https://login.microsoftonline.com/" + tenant, true, service);

            Future<AuthenticationResult> future = context.acquireToken(
                    resourceId, clientAssertion, clientCredential,
                    null);

            result = future.get();
        } finally {
            service.shutdown();
        }

        if (result == null) {
            throw new ServiceUnavailableException("authentication result was null");
        }
        return result;
    }
```

But I keep getting an error: 

> {"error_description":"AADSTS70002: Error validating credentials. AADSTS50013: Assertion audience claim does not match the required value.\r\nTrace ID: 0de7c901-7f0b-4c8d-8e0c-16c94dbdd35f\r\nCorrelation ID: 7cbdc1ec-2ba8-4116-939f-575680d29934\r\nTimestamp: 2015-10-20 13:07:20Z","error":"invalid_grant"}

As I can see in the code it is using:
requested_token_use=on_behalf_of
grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer

so at first look it should work. 

I was trying to simulate this also using CURL:

> curl -i -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" --request POST https://login.microsoftonline.com/miappdev.org/oauth2/token -d 'client_id=CLIENT_ID&client_secret=CLIENT_SECRET&resource=RESOURCE&requested_token_use=on_behalf_of&scope=user_impersonation&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=JWT_TOKEN_OF_SIGNED_IN_USER'

but the result is exactly the same.

Should I be able to use some signed-in user's JWT token to access i.e. graph.windows.net on behalf of him? Or is there some misunderstanding?

**Comment by ranganathg** [comment]
There are some pre-reqs for using Graph Apis in an app - https://msdn.microsoft.com/en-us/library/azure/hh974476.aspx#Anchor_2
