### ISSUE TITLE
Maven GroupId does not match package names

### ISSUE THREAD

**Issue by jianghaolu** [AzureAD/azure-activedirectory-library-for-java#74]
Hi,

I see from this commit: https://github.com/AzureAD/azure-activedirectory-library-for-java/commit/e083290365a8b6e1ef6534cbfdfe162d768c3fc2 that group id was changed to com.microsoft.azure but the package names were left unchanged. This is uncommon and makes it hard to discover.

Also, it collides with the package names in ADAL for android. This is making it really hard for a cross-platform library (run on both JDK and Android) to tell which library is loaded.

**Comment by jianghaolu** [comment]
@martinsawicki

**Comment by kpanwar** [comment]
We will fix this in the next major version to avoid breaking changes.

**Comment by kpanwar** [comment]
We will update the source code package to com.microsoft.azure
