### ISSUE TITLE
How do I run the java webapp sample, Get an error saying "No main class"

### ISSUE THREAD

**Issue by moezubair** [AzureAD/azure-activedirectory-library-for-java#79]
Hey
I am trying to run the sample java web app 
when I run the war file I get :

```
no main manifest attribute, in target/adal4jsample.war
```

when I run it as 

```
mvn spring-boot:run

```

I get :

```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) on project adal4jsample: Unable to find a suitable main class, please add a 'mainClass' property -> [Help 1]
```

**Comment by amignano** [comment]
In your POM try adding

`
<plugin>
<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<mainClass>com.places.Main</mainClass>
	</configuration>
</plugin>
`

**Comment by Xfox1** [comment]
In your POM try adding

`<plugin> <groupId>org.springframework.boot</groupId> <artifactId>spring-boot-maven-plugin</artifactId> <configuration> <mainClass>com.places.Main</mainClass> </configuration> </plugin>`
