### ISSUE TITLE
adal4j compatible with jdk1.6 version

### ISSUE THREAD

**Issue by mathewvino** [AzureAD/azure-activedirectory-library-for-java#87]
Is there any version of adal4j compatible with jDK1.6 available. I was trying to run some junit test case using adal4j with jdk1.6  getting the following error

Caused by: java.lang.UnsupportedClassVersionError: com/nimbusds/jose/Algorithm : Unsupported major.minor version 51.0

Really appreciate
Vinoj

**Comment by kpanwar** [comment]
Minimum supported is 1.7 due to security fixes.

**Comment by sathishscjp1** [comment]
Cant we run ADAL4j for web application which is running JRE 1.6
