### ISSUE TITLE
XXE vulnerability in WSTrustResponse.java 

### ISSUE THREAD

**Issue by gursev** [AzureAD/azure-activedirectory-library-for-java#92]
There is an XXE bug in WSTrustResponse's parse method. Please see below.

    static WSTrustResponse parse(String response, WSTrustVersion version)
            throws Exception {
        WSTrustResponse responseValue = new WSTrustResponse();
        DocumentBuilderFactory builderFactory = DocumentBuilderFactory
                .newInstance();
        builderFactory.setNamespaceAware(true);
        DocumentBuilder builder = builderFactory.newDocumentBuilder();
        Document xmlDocument = builder.parse(new ByteArrayInputStream(response
                .getBytes(Charset.forName("UTF-8")))); **//XXE Bug**
        XPath xPath = XPathFactory.newInstance().newXPath();

**Comment by gursev** [comment]
@brandwe Fyi. Can you please label it as a security bug?

**Comment by brandwe** [comment]
@gursev Done

**Comment by gursev** [comment]
@brandwe Thank you so much.

**Comment by kpanwar** [comment]
Fixed in 1.1.3

**Comment by gursev** [comment]
@brandwe @kpanwar Thank you so much for the quick fixes and pushing to Maven 👍
