### ISSUE TITLE
XXE vulnerability in MexParser

### ISSUE THREAD

**Issue by gursev** [AzureAD/azure-activedirectory-library-for-java#93]
static BindingPolicy getWsTrustEndpointFromMexResponse(String mexResponse)
            throws Exception {
        DocumentBuilderFactory builderFactory = DocumentBuilderFactory
                .newInstance();
        builderFactory.setNamespaceAware(true);
        DocumentBuilder builder = builderFactory.newDocumentBuilder();
        Document xmlDocument = builder.parse(new ByteArrayInputStream(
                mexResponse.getBytes(Charset.forName("UTF-8")))); **//** **XXE Bug**

        XPath xPath = XPathFactory.newInstance().newXPath();

**Comment by gursev** [comment]
@brandwe Fyi. Can you please label it as a security bug?

**Comment by brandwe** [comment]
@gursev Done.

**Comment by gursev** [comment]
@brandwe Thank you so much.

**Comment by kpanwar** [comment]
Fixed in 1.1.3.
