### ISSUE TITLE
Add API that allows apps to report app name and version for telemetry.

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-java#98]
It would be helpful to be able to identify which apps have which version of ADAL so that we can identify apps that should be updated.

Do not implement this until we have agreement on the shape of the public API changes.

**Comment by sangonzal** [comment]
ADAL4J is in maintenance mode and no new features will be added going forward except for security fixes. All our ongoing efforts will be focused on improving MSAL4J. This feature has already been added to MSAL.
